-- SAP AI Core & Generative AI Assessment Questions (order_num 1-150)
-- Run AFTER ensuring the sap-ai course exists in the courses table
INSERT INTO public.assessment_questions
  (course_id, question, options, correct_option, explanation, topic_slug, order_num)
VALUES
('sap-ai',
 'What is SAP AI Core primarily designed for?',
 '["Training and running AI/ML models at scale on BTP infrastructure", "Building SAPUI5 frontends", "Managing SAP ERP master data", "Providing HANA Cloud database services"]',
 0,
 'SAP AI Core is BTP''s managed MLOps platform for executing AI pipelines (training, serving) using Argo Workflows and Kubernetes.',
 'ai-intro-test', 1),
('sap-ai',
 'Which orchestration engine does SAP AI Core use to run ML training pipelines?',
 '["Argo Workflows", "Apache Airflow", "Kubernetes Jobs", "SAP Data Intelligence Pipelines"]',
 0,
 'SAP AI Core uses Argo Workflows (a Kubernetes-native workflow engine) to define and execute multi-step ML training pipelines.',
 'ai-intro-test', 2),
('sap-ai',
 'In SAP AI Core, what is a ''Resource Group''?',
 '["A logical namespace that isolates AI workloads and data for a tenant or team", "A set of GPU nodes in a cluster", "A collection of AI models", "An XSUAA role collection"]',
 0,
 'Resource Groups provide tenant isolation within AI Core, separating configurations, deployments, artifacts, and secrets per group.',
 'ai-intro-test', 3),
('sap-ai',
 'What is the role of the ''AI API'' in SAP AI Core?',
 '["A REST API that provides a unified interface to manage scenarios, executions, deployments, and artifacts", "A Python library for building neural networks", "A Fiori app for monitoring ML models", "An OData service for reading training data"]',
 0,
 'The AI API is the single REST interface for AI Core and AI Launchpad, covering the full MLOps lifecycle from configuration to model serving.',
 'ai-intro-test', 4),
('sap-ai',
 'Which SAP BTP service provides a user interface for managing AI Core workloads?',
 '["SAP AI Launchpad", "SAP Build Apps", "SAP Analytics Cloud", "SAP Integration Suite"]',
 0,
 'SAP AI Launchpad is the Fiori-based cockpit that provides a UI over AI Core''s AI API for managing scenarios, runs, and deployments.',
 'ai-intro-test', 5),
('sap-ai',
 'In SAP AI Core, what is a ''Scenario''?',
 '["A grouping of related AI use cases with their associated executables and artifacts", "A single training run", "A deployed model endpoint", "A Kubernetes namespace"]',
 0,
 'A Scenario organizes executables (training/serving templates) and artifacts (datasets, models) for a specific AI use case.',
 'ai-intro-test', 6),
('sap-ai',
 'Which cloud hyperscalers can host SAP AI Core infrastructure?',
 '["AWS, Azure, and Google Cloud Platform", "Only AWS", "Only Azure", "On-premise SAP data centers only"]',
 0,
 'SAP AI Core is a hyperscaler-agnostic managed service available on AWS, Azure, and GCP as part of SAP BTP''s multi-cloud strategy.',
 'ai-intro-test', 7),
('sap-ai',
 'What does ''bring your own container'' mean in SAP AI Core?',
 '["Users supply Docker images with their ML code; AI Core executes them on managed infrastructure", "AI Core provides pre-built containers only", "Users deploy models as Lambda functions", "Custom code runs inside HANA Cloud"]',
 0,
 'AI Core''s execution model requires users to package ML training/serving code as Docker images pushed to a container registry, giving full flexibility.',
 'ai-intro-test', 8),
('sap-ai',
 'What is the purpose of ''Object Store Secret'' in SAP AI Core?',
 '["Storing credentials for S3/Azure Blob/GCS object storage to access training data and model artifacts", "Encrypting model weights at rest", "Managing XSUAA client secrets", "Configuring SAP HANA Cloud credentials"]',
 0,
 'AI Core uses Object Store Secrets to securely reference cloud storage credentials, allowing training pipelines to read data and write model artifacts.',
 'ai-intro-test', 9),
('sap-ai',
 'In SAP AI Core, what is a ''Docker Registry Secret''?',
 '["Credentials that allow AI Core to pull private Docker images from a container registry", "A secret key for encrypting Docker images", "A CF service binding for Docker Hub", "An XSUAA scope for container access"]',
 0,
 'Docker Registry Secrets store the authentication credentials (server, username, password) AI Core needs to pull private images from registries like Docker Hub or ACR.',
 'ai-intro-test', 10),
('sap-ai',
 'What format does SAP AI Core use to define training pipeline templates?',
 '["Argo Workflow YAML (workflow templates)", "Kubernetes Deployment YAML", "SAP-specific XML", "Python class definitions"]',
 0,
 'AI Core training pipelines are defined as Argo Workflow templates in YAML, registered via the AI API as ''executables''.',
 'ai-scenarios-test', 11),
('sap-ai',
 'Which Git-based process does SAP AI Core use to register workflow templates?',
 '["Git-ops: templates are committed to a Git repo and AI Core syncs via an Application/GitOps binding", "Direct file upload via AI API", "CF push of YAML files", "BTP subaccount configuration UI"]',
 0,
 'AI Core uses a GitOps model: workflow YAMLs are committed to a connected Git repo, and AI Core syncs and registers them as executables automatically.',
 'ai-scenarios-test', 12),
('sap-ai',
 'In SAP AI Core, what is an ''Executable''?',
 '["A registered workflow template that defines the steps of a training or batch inferencing pipeline", "A deployed model endpoint URL", "A running Kubernetes pod", "A Python script uploaded to AI Core"]',
 0,
 'Executables are the templates (Argo Workflows) registered in AI Core that define parameterized training or batch pipelines, versioned within a scenario.',
 'ai-scenarios-test', 13),
('sap-ai',
 'How do you pass dynamic parameters to a training run in SAP AI Core?',
 '["Via ''parameterBindings'' in the Execution configuration when creating a Run", "Via environment variables in the Docker image", "By modifying the workflow YAML before each run", "Through a config file in the Object Store"]',
 0,
 'When creating a Run (Execution), you supply parameterBindings that override the default parameter values defined in the workflow template.',
 'ai-scenarios-test', 14),
('sap-ai',
 'What is the difference between a ''Configuration'' and an ''Execution'' in SAP AI Core?',
 '["A Configuration combines an executable + parameter/input bindings; an Execution is a run of that Configuration", "Both are the same thing", "Execution defines parameters; Configuration runs them", "Configuration is for deployments; Execution is for training only"]',
 0,
 'A Configuration is the reusable parameterized spec (which executable, which dataset, which hyperparameters). An Execution instantiates a Configuration into an actual run.',
 'ai-scenarios-test', 15),
('sap-ai',
 'In SAP AI Core, what is a ''Deployment''?',
 '["A long-running model serving endpoint that exposes the model as a REST API", "A one-off training pipeline run", "A Docker image stored in a registry", "A Git repository containing model code"]',
 0,
 'A Deployment in AI Core runs a serving workflow as a persistent service with a URL endpoint, enabling real-time inference requests.',
 'ai-deployments-test', 16),
('sap-ai',
 'What HTTP method is used to send an inference request to a deployed model in SAP AI Core?',
 '["POST", "GET", "PUT", "PATCH"]',
 0,
 'Inference requests send input data to the model endpoint, requiring POST with a JSON body containing the prompt or feature vector.',
 'ai-deployments-test', 17),
('sap-ai',
 'Which SAP AI Core API endpoint is used to list all active deployments in a resource group?',
 '["GET /v2/lm/deployments", "GET /v2/lm/executions", "POST /v2/lm/deployments", "GET /v2/scenarios"]',
 0,
 'GET /v2/lm/deployments (with the ai-resource-group header) lists all deployments and their status in that resource group.',
 'ai-deployments-test', 18),
('sap-ai',
 'What is a ''Serving Executable'' in SAP AI Core?',
 '["An Argo Workflow or Kubernetes Deployment template defining how a model is served (loaded and exposed as API)", "The trained model file stored in S3", "A Python function that computes predictions", "A Fiori UI for model monitoring"]',
 0,
 'A serving executable defines the deployment template — container image, resource requirements, and serving framework (e.g. Triton, TorchServe).',
 'ai-deployments-test', 19),
('sap-ai',
 'What status indicates a deployment is healthy and accepting inference requests in AI Core?',
 '["RUNNING", "PENDING", "COMPLETED", "STOPPED"]',
 0,
 'A deployment in RUNNING state has successfully started the serving container and is actively accepting HTTP inference requests at its URL.',
 'ai-deployments-test', 20),
('sap-ai',
 'In SAP AI Core, what is the ''deploymentUrl'' used for?',
 '["It is the base URL appended with ''/v1/predict'' (or similar) to send inference requests", "It is the URL to the AI Launchpad UI", "It is the Docker registry URL", "It is the Git repository URL for model code"]',
 0,
 'deploymentUrl is the AI Core-managed endpoint URL. Clients append the path (e.g. /v1/models/my-model:predict) to route to the serving container.',
 'ai-deployments-test', 21),
('sap-ai',
 'How do you stop a running deployment in SAP AI Core?',
 '["PATCH /v2/lm/deployments/{id} with targetStatus: STOPPED", "DELETE /v2/lm/deployments/{id}", "POST /v2/lm/deployments/{id}/stop", "cf stop deployment-app"]',
 0,
 'AI Core uses a PATCH request with targetStatus: STOPPED to gracefully shut down a running deployment and release its resources.',
 'ai-deployments-test', 22),
('sap-ai',
 'What resource type does a model artifact represent in SAP AI Core?',
 '["A registered artifact of kind MODEL pointing to the trained model files in Object Store", "A Docker image in the registry", "A Kubernetes ConfigMap", "A training configuration JSON"]',
 0,
 'After training, the model files are uploaded to Object Store and registered as an Artifact with kind: MODEL, which serving configurations reference.',
 'ai-deployments-test', 23),
('sap-ai',
 'What is ''ttl'' (time-to-live) in the context of an SAP AI Core deployment?',
 '["Maximum duration the deployment runs before auto-stopping", "Network packet lifetime", "Model cache expiry", "Token expiry for the serving endpoint JWT"]',
 0,
 'ttl defines how long a deployment runs before AI Core automatically stops it, useful for cost control in scheduled or batch serving scenarios.',
 'ai-deployments-test', 24),
('sap-ai',
 'Which authentication mechanism does SAP AI Core use to secure inference endpoint calls?',
 '["OAuth 2.0 Bearer token (XSUAA client credentials)", "API key in query string", "Basic authentication", "No authentication (public endpoint)"]',
 0,
 'AI Core deployments require a valid OAuth token (from XSUAA using client credentials) in the Authorization: Bearer header for all inference calls.',
 'ai-deployments-test', 25),
('sap-ai',
 'What is the SAP Generative AI Hub?',
 '["A managed service that provides access to multiple LLMs (GPT-4, Claude, Gemini, etc.) through a unified API on BTP", "A SAP-developed large language model", "A vector database for embeddings", "A Fiori app for writing prompts"]',
 0,
 'The Generative AI Hub in SAP AI Launchpad provides a unified API surface (harmonized with OpenAI standards) to access foundation models from multiple providers.',
 'ai-genai-hub-test', 26),
('sap-ai',
 'Which API standard does the SAP Generative AI Hub harmonize with for LLM calls?',
 '["OpenAI API (chat completions)", "Hugging Face Inference API", "Google Vertex AI API", "A proprietary SAP API"]',
 0,
 'The Generative AI Hub exposes an OpenAI-compatible API (/chat/completions, /embeddings) so existing OpenAI SDK code works with minimal changes.',
 'ai-genai-hub-test', 27),
('sap-ai',
 'Which Python package provides the official SAP client for Generative AI Hub?',
 '["generative-ai-hub-sdk (from SAP)", "openai", "anthropic", "transformers"]',
 0,
 'The ''generative-ai-hub-sdk'' (pip install generative-ai-hub-sdk) is SAP''s Python SDK that wraps the AI Core AI API with convenient client classes.',
 'ai-sdk-test', 28),
('sap-ai',
 'What model name is used to access GPT-4o through the SAP Generative AI Hub?',
 '["gpt-4o (the deployment name configured in AI Core)", "sap-gpt4o", "azure-openai-gpt4o", "genai-gpt-4"]',
 0,
 'The deployment name in AI Core (which maps to the actual model) is used as the ''model'' parameter. For Azure OpenAI models, SAP configures the deployment to match the official model name.',
 'ai-genai-hub-test', 29),
('sap-ai',
 'In the SAP Generative AI Hub Python SDK, which class is used to call a chat completion model?',
 '["AzureOpenAI (or OpenAI-compatible client with AI Core base URL)", "ChatGPT", "SAPGenAIClient", "BTPLLMClient"]',
 0,
 'The SDK re-exports an OpenAI-compatible client configured with AI Core credentials, so you use it like the standard OpenAI Python SDK.',
 'ai-sdk-test', 30),
('sap-ai',
 'What is ''orchestration'' in the SAP Generative AI Hub context?',
 '["A managed pipeline that combines LLM calls, grounding (RAG), input filtering, and templating in one API call", "Running multiple models in parallel", "A Kubernetes orchestration layer", "Workflow automation with Argo"]',
 0,
 'The Orchestration Service in Generative AI Hub lets you define a pipeline: template + grounding + LLM call + content filters — all in a single API request.',
 'ai-orchestration-test', 31),
('sap-ai',
 'What is the ''grounding'' feature in SAP Generative AI Hub orchestration?',
 '["Injecting retrieved context (RAG chunks) into the prompt automatically during orchestration", "Fine-tuning the model on domain data", "Connecting the LLM to the internet", "Caching model responses"]',
 0,
 'Grounding in orchestration retrieves relevant document chunks from a vector store and injects them into the prompt context, implementing RAG transparently.',
 'ai-orchestration-test', 32),
('sap-ai',
 'Which content safety capability does SAP Generative AI Hub''s orchestration support?',
 '["Input and output content filtering (e.g. detecting harmful content via Azure Content Safety or SAP filters)", "Grammar checking", "PII encryption", "Image moderation only"]',
 0,
 'Orchestration pipelines can include content filter modules that screen prompts and responses for harmful, inappropriate, or sensitive content before delivery.',
 'ai-orchestration-test', 33),
('sap-ai',
 'In the Generative AI Hub, what is a ''prompt template''?',
 '["A parameterized text template with placeholders ({{variable}}) rendered with runtime values before sending to the LLM", "A saved conversation history", "A fine-tuned model checkpoint", "A Kubernetes ConfigMap"]',
 0,
 'Prompt templates define the structure of the prompt with variable placeholders. At runtime, the orchestration service fills in values and sends the rendered prompt to the LLM.',
 'ai-prompt-test', 34),
('sap-ai',
 'What does ''token'' mean in the context of LLM pricing and limits?',
 '["A sub-word unit used by the tokenizer; pricing and context windows are measured in tokens", "An OAuth access token", "A unique identifier for a model", "A training data record"]',
 0,
 'LLMs process text as tokens (roughly 4 characters or 0.75 words in English). Context window limits and API costs are measured per token.',
 'ai-genai-hub-test', 35),
('sap-ai',
 'What is ''temperature'' in an LLM API call?',
 '["A sampling parameter (0-2) controlling randomness: 0 = deterministic, higher = more creative", "The CPU temperature of the GPU server", "The time-to-first-token latency", "The model''s confidence score"]',
 0,
 'Temperature controls the probability distribution sharpness during token sampling. Lower values make output more focused; higher values increase diversity/creativity.',
 'ai-genai-hub-test', 36),
('sap-ai',
 'What is ''max_tokens'' in an LLM API request?',
 '["The maximum number of tokens the model generates in its response", "The total tokens in the prompt", "The model''s context window size", "The batch size for embedding generation"]',
 0,
 'max_tokens caps the length of the generated response, preventing excessively long outputs and controlling cost.',
 'ai-genai-hub-test', 37),
('sap-ai',
 'In the OpenAI-compatible API, what is the ''system'' message role used for?',
 '["Setting the assistant''s behavior, persona, and constraints at the start of a conversation", "Logging system events", "Storing conversation history", "Defining the function/tool schema"]',
 0,
 'The system message sets the overall context and instructions for the assistant (e.g. ''You are a helpful SAP developer assistant''). It is processed before user messages.',
 'ai-prompt-test', 38),
('sap-ai',
 'What does ''streaming'' in an LLM API call mean?',
 '["The model sends tokens incrementally as they are generated (server-sent events) instead of waiting for the full response", "Uploading training data as a stream", "Real-time data ingestion for fine-tuning", "WebSocket connection for model updates"]',
 0,
 'With stream: true, the API returns a chunked response (SSE) with each generated token, enabling progressive display in UIs like ChatGPT.',
 'ai-genai-hub-test', 39),
('sap-ai',
 'Which SAP Generative AI Hub feature allows calling external tools or APIs based on the model''s decision?',
 '["Function Calling (Tool Use)", "Grounding", "Content Filtering", "Prompt Templates"]',
 0,
 'Function/Tool calling lets you define available functions; the model decides when to call them and returns a structured call request that your code executes.',
 'ai-genai-hub-test', 40),
('sap-ai',
 'What is ''few-shot prompting''?',
 '["Including example input-output pairs in the prompt to guide the model''s response format", "Training the model on a few examples", "Using a very short prompt", "Providing few system instructions"]',
 0,
 'Few-shot prompting embeds 2-5 worked examples (input → output) in the prompt, teaching the model the expected pattern without parameter updates.',
 'ai-prompt-test', 41),
('sap-ai',
 'What is ''chain-of-thought'' (CoT) prompting?',
 '["Instructing the model to reason step-by-step before giving the final answer, improving accuracy on complex tasks", "Chaining multiple model API calls", "Using a chain of if-else logic in the prompt", "Training with chain data"]',
 0,
 'CoT prompting (e.g. ''Think step by step'') encourages the model to produce intermediate reasoning steps, dramatically improving performance on math, logic, and multi-step problems.',
 'ai-prompt-test', 42),
('sap-ai',
 'What is ''zero-shot prompting''?',
 '["Asking the model to perform a task with no examples, relying on pre-trained knowledge", "Training with zero data", "A prompt with no system message", "Calling the model with empty input"]',
 0,
 'Zero-shot prompting gives the model only the task description and trusts its pre-training to generalize — no examples are provided.',
 'ai-prompt-test', 43),
('sap-ai',
 'What is ''prompt injection''?',
 '["An attack where malicious user input overrides the system prompt, hijacking the model''s behavior", "SQL injection adapted for databases", "A method to inject context into embeddings", "A technique to increase prompt tokens"]',
 0,
 'Prompt injection occurs when user-supplied text manipulates the LLM into ignoring safety instructions or performing unintended actions — a key security concern.',
 'ai-prompt-test', 44),
('sap-ai',
 'What does ''grounding'' a prompt mean (outside of orchestration)?',
 '["Providing factual context (documents, database results) in the prompt to reduce hallucinations", "Fine-tuning the model", "Adjusting temperature to 0", "Using a retrieval system only"]',
 0,
 'Grounding anchors the model''s response to real, retrieved information rather than relying on potentially outdated or hallucinated training knowledge.',
 'ai-prompt-test', 45),
('sap-ai',
 'What is a ''hallucination'' in LLM outputs?',
 '["Confidently stated but factually incorrect information generated by the model", "A visual artifact in image generation", "Model uncertainty expressed as a probability", "Repeating the same sentence multiple times"]',
 0,
 'LLM hallucinations are plausible-sounding but factually wrong statements the model generates when it lacks knowledge — a core challenge RAG aims to address.',
 'ai-prompt-test', 46),
('sap-ai',
 'In prompt design, what is ''role prompting''?',
 '["Assigning a persona to the model (''Act as an SAP consultant'') to shape the style and focus of responses", "Setting the XSUAA role", "Defining function roles in tool calling", "Configuring system roles in Kubernetes"]',
 0,
 'Role prompting assigns a specific persona or expertise area, biasing the model''s vocabulary, tone, and assumed knowledge domain.',
 'ai-prompt-test', 47),
('sap-ai',
 'What is the ''context window'' of an LLM?',
 '["The maximum number of tokens (prompt + response) the model can process in one call", "The browser viewport size", "The training dataset size", "The GPU memory available"]',
 0,
 'The context window limits how much text the model can ''see'' at once. GPT-4 Turbo''s 128k context allows very large documents or long conversations.',
 'ai-genai-hub-test', 48),
('sap-ai',
 'What does the ''top_p'' parameter control in LLM sampling?',
 '["Nucleus sampling: restricts token selection to the smallest set whose cumulative probability reaches top_p", "The number of response tokens", "The model''s training step", "The API rate limit"]',
 0,
 'top_p = 0.9 means the model samples only from tokens whose cumulative probability is 90%, dynamically trimming low-probability options for more coherent output.',
 'ai-genai-hub-test', 49),
('sap-ai',
 'What is ''retrieval-augmented generation'' (RAG)?',
 '["Combining a retrieval system (vector search over documents) with an LLM to answer questions using current, specific data", "Training a model on retrieved documents", "A method of fine-tuning with synthetic data", "Searching the web during generation"]',
 0,
 'RAG retrieves relevant document chunks using semantic search, then provides them as context to the LLM, enabling accurate answers from private or recent data.',
 'ai-rag-test', 50),
('sap-ai',
 'What is a ''vector embedding''?',
 '["A dense numerical representation of text that captures semantic meaning, enabling similarity search", "A sparse TF-IDF feature vector", "A Base64-encoded string", "A cryptographic hash of text"]',
 0,
 'Embedding models convert text into high-dimensional floating-point vectors where semantically similar texts are close together in vector space.',
 'ai-rag-test', 51),
('sap-ai',
 'What does ''cosine similarity'' measure in the context of vector embeddings?',
 '["The angle between two vectors \u2014 values near 1 indicate high semantic similarity", "The Euclidean distance between embeddings", "The dot product magnitude", "The embedding model''s confidence"]',
 0,
 'Cosine similarity (cosine of the angle) is the standard metric for comparing embeddings: 1 = identical, 0 = orthogonal (unrelated), -1 = opposite.',
 'ai-rag-test', 52),
('sap-ai',
 'What is a ''vector store'' (vector database)?',
 '["A database optimized for storing embeddings and performing fast approximate nearest-neighbor (ANN) search", "A key-value store for model weights", "A SQL database with vector columns only", "A message queue for embedding updates"]',
 0,
 'Vector stores (e.g. HANA Cloud vector engine, ChromaDB, Pinecone) index embeddings for efficient similarity search over millions of documents.',
 'ai-rag-test', 53),
('sap-ai',
 'In SAP HANA Cloud, which SQL function is used to compute cosine similarity between stored vectors?',
 '["COSINE_SIMILARITY(embedding_col, query_vector)", "DOT_PRODUCT(embedding_col, query_vector)", "VECTOR_COMPARE(embedding_col, query_vector)", "L2_DISTANCE(embedding_col, query_vector)"]',
 0,
 'SAP HANA Cloud''s vector engine provides COSINE_SIMILARITY as a SQL function for semantic similarity queries against stored embedding columns.',
 'ai-rag-test', 54),
('sap-ai',
 'What data type stores a vector embedding in SAP HANA Cloud?',
 '["REAL_VECTOR", "VECTOR", "FLOAT_ARRAY", "JSON"]',
 0,
 'HANA Cloud introduced the REAL_VECTOR data type for storing fixed-dimension floating-point embedding vectors with native similarity functions.',
 'ai-rag-test', 55),
('sap-ai',
 'What is ''chunking'' in a RAG pipeline?',
 '["Splitting documents into smaller segments so embeddings capture focused semantics and fit model context windows", "Compressing model weights", "Batching API calls", "Splitting training data for distributed training"]',
 0,
 'Documents are chunked into paragraphs or fixed-size token windows before embedding, so each chunk has focused semantics and can be retrieved independently.',
 'ai-rag-test', 56),
('sap-ai',
 'What is ''top-k retrieval'' in RAG?',
 '["Fetching the k most similar document chunks to a query embedding", "Selecting the top k tokens by probability", "Choosing k training examples", "Limiting API responses to k tokens"]',
 0,
 'Top-k retrieval returns the k chunks with highest similarity to the query embedding, which are then injected as context into the LLM prompt.',
 'ai-rag-test', 57),
('sap-ai',
 'Which embedding model can be accessed through SAP Generative AI Hub?',
 '["text-embedding-ada-002 (Azure OpenAI) and other configured models", "Only SAP proprietary embedding models", "No embedding models \u2014 only chat models", "BERT fine-tuned on SAP data"]',
 0,
 'Via the Generative AI Hub, you can access Azure OpenAI''s text-embedding-ada-002 (and newer models) using the standard /embeddings endpoint.',
 'ai-genai-hub-test', 58),
('sap-ai',
 'In a RAG system, what is the risk of too-large chunks?',
 '["The embedding captures too much mixed content, reducing retrieval precision", "The chunk won''t fit in the context window", "Too-large chunks increase embedding model cost only", "There is no risk; larger chunks always work better"]',
 0,
 'Large chunks dilute the semantic signal in the embedding, making it harder to retrieve the right chunk for a specific query. Smaller focused chunks yield better precision.',
 'ai-rag-test', 59),
('sap-ai',
 'What is ''hybrid search'' in RAG?',
 '["Combining dense vector (semantic) search with sparse keyword (BM25/TF-IDF) search for better retrieval", "Using two different LLMs together", "Merging embedding models", "Searching both HANA and a vector DB simultaneously"]',
 0,
 'Hybrid search combines semantic similarity (embeddings) with keyword matching (BM25), capturing both conceptual relevance and exact term matches.',
 'ai-rag-test', 60),
('sap-ai',
 'What Python library does SAP recommend for building RAG pipelines that integrate with Generative AI Hub?',
 '["LangChain or LlamaIndex with AI Core adapter", "PyTorch only", "SAP''s custom RAG library", "Scikit-learn"]',
 0,
 'LangChain and LlamaIndex provide RAG pipeline abstractions (document loaders, text splitters, vector stores, LLM chains) and can be configured to use AI Core as the LLM backend.',
 'ai-sdk-test', 61),
('sap-ai',
 'What is ''re-ranking'' in a RAG pipeline?',
 '["A second-pass model (e.g. cross-encoder) that scores retrieved chunks more precisely before injecting into the LLM", "Running the retrieval query twice", "Sorting embedding results by timestamp", "Filtering chunks by length"]',
 0,
 'Cross-encoder re-rankers compare query + chunk pairs directly and produce a more accurate relevance score than bi-encoder embeddings, improving final context quality.',
 'ai-rag-test', 62),
('sap-ai',
 'What is ''semantic chunking''?',
 '["Splitting documents at semantically meaningful boundaries (sentences, paragraphs) rather than fixed token counts", "Random splitting of text", "Splitting by file size", "Chunking based on document metadata"]',
 0,
 'Semantic chunking preserves coherent meaning units, avoiding splits mid-sentence or mid-concept, which would degrade embedding quality.',
 'ai-rag-test', 63),
('sap-ai',
 'In a RAG pipeline, what is ''query expansion''?',
 '["Generating multiple paraphrased versions of the user query to retrieve more diverse relevant chunks", "Increasing the max_tokens of the query", "Adding metadata to the query", "Translating the query to another language"]',
 0,
 'Query expansion generates variations or sub-questions from the original query, improving recall when the document and query use different vocabulary.',
 'ai-rag-test', 64),
('sap-ai',
 'What is the SAP HANA Cloud ''vector engine'' capability?',
 '["Native support for storing REAL_VECTOR embeddings and running SQL-based similarity search without a separate vector DB", "A separate BTP service for vector storage", "A Python library for HANA vector operations", "A CF buildpack for running vector DBs"]',
 0,
 'HANA Cloud''s vector engine lets you store embeddings alongside relational data and query them with COSINE_SIMILARITY or L2_DISTANCE in standard SQL.',
 'ai-rag-test', 65),
('sap-ai',
 'What is the correct pip install command for the SAP AI Core Python SDK?',
 '["pip install ai-core-sdk", "pip install sap-ai-core", "pip install generative-ai-hub-sdk", "pip install sap-ml-sdk"]',
 0,
 'The SAP AI Core SDK package is ''ai-core-sdk'', which provides AICoreClient for managing scenarios, configurations, runs, and deployments via Python.',
 'ai-sdk-test', 66),
('sap-ai',
 'In the SAP AI Core Python SDK, how do you create an AICoreClient from service key credentials?',
 '["AICoreClient(base_url=..., auth_url=..., client_id=..., client_secret=...)", "AICoreClient.from_env()", "AICoreClient(service_key_path=''key.json'')", "AICoreClient(btp_token=...)"]',
 0,
 'You instantiate AICoreClient with the auth_url, base_url, client_id, and client_secret from the AI Core service key JSON.',
 'ai-sdk-test', 67),
('sap-ai',
 'What does the following code do?

from ai_core_sdk.ai_core_v2_client import AICoreV2Client
client = AICoreV2Client(base_url=BASE_URL, auth_url=AUTH_URL,
    client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
deployments = client.deployment.query(resource_group=''default'').resources',
 '["Lists all deployments in the ''default'' resource group", "Creates a new deployment", "Deletes all deployments", "Trains a model"]',
 0,
 'client.deployment.query() calls GET /v2/lm/deployments and returns a DeploymentList; .resources gives the list of Deployment objects.',
 'ai-sdk-test', 68),
('sap-ai',
 'How do you send a chat completion request using the SAP Generative AI Hub SDK?',
 '["from gen_ai_hub.proxy.native.openai import init_models; then use an OpenAI-compatible client", "import sap_llm; sap_llm.chat(messages)", "AICoreClient.chat(model=''gpt-4'', messages=[...])", "requests.post(AI_CORE_URL + ''/chat'', json={''messages'': [...]})"]',
 0,
 'The gen_ai_hub SDK provides an OpenAI-compatible proxy client configured with AI Core credentials, wrapping the standard OpenAI Python SDK interface.',
 'ai-sdk-test', 69),
('sap-ai',
 'What environment variable file does the SAP Generative AI Hub SDK look for to auto-configure credentials?',
 '[".env file with AICORE_AUTH_URL, AICORE_CLIENT_ID, AICORE_CLIENT_SECRET, AICORE_BASE_URL", "config.yaml", "credentials.json", "VCAP_SERVICES JSON"]',
 0,
 'The SDK reads AICORE_* environment variables (or a .env file via python-dotenv) to configure the client without hardcoding credentials.',
 'ai-sdk-test', 70),
('sap-ai',
 'What does this code output?

from gen_ai_hub.proxy.langchain.openai import ChatOpenAI
llm = ChatOpenAI(proxy_model_name=''gpt-4o'')
result = llm.invoke(''What is CAP?'')
print(result.content)',
 '["The LLM''s text response about CAP, routed through SAP Generative AI Hub", "An error because ChatOpenAI requires OpenAI key", "A training run ID", "An embedding vector"]',
 0,
 'gen_ai_hub''s LangChain-compatible ChatOpenAI proxy routes the invoke call to GPT-4o via AI Core, returning an AIMessage with the LLM''s response in .content.',
 'ai-sdk-test', 71),
('sap-ai',
 'Which LangChain class is used with AI Core for generating text embeddings?',
 '["OpenAIEmbeddings from gen_ai_hub.proxy.langchain.openai", "SAPEmbeddings from ai_core_sdk", "AICoreEmbeddingModel", "BTPEmbeddingClient"]',
 0,
 'gen_ai_hub provides LangChain-compatible embedding wrappers (OpenAIEmbeddings proxy) that route embedding calls through AI Core to the configured model.',
 'ai-sdk-test', 72),
('sap-ai',
 'How do you use AI Core credentials from a VCAP_SERVICES environment variable in the Python SDK?',
 '["The SDK can parse VCAP_SERVICES automatically when aicore is a bound CF service", "You must manually extract and pass them", "VCAP_SERVICES is not supported; use .env only", "You need a custom parser"]',
 0,
 'When deployed on CF with AI Core service binding, VCAP_SERVICES contains the credentials. The SDK can read them automatically via its CF integration.',
 'ai-sdk-test', 73),
('sap-ai',
 'What is the correct way to set the resource group for all AI Core SDK calls?',
 '["Pass resource_group parameter per call, or set it as default on the client", "Set RESOURCE_GROUP env variable", "Configure it in mta.yaml", "It is always ''default'' and cannot be changed"]',
 0,
 'Each SDK method that is resource-group-scoped accepts a resource_group parameter. Some client wrappers also support setting a default resource group on initialization.',
 'ai-sdk-test', 74),
('sap-ai',
 'What is the output of this Python snippet?

import json
from ai_core_sdk.models import ParameterBinding

bindings = [ParameterBinding(key=''learning_rate'', value=''0.001'')]
print(json.dumps([b.__dict__ for b in bindings]))',
 '["[{\"key\": \"learning_rate\", \"value\": \"0.001\"}]", "[{\"learning_rate\": 0.001}]", "[\"learning_rate=0.001\"]", "ParameterBinding object at 0x..."]',
 0,
 'ParameterBinding is a simple dataclass; __dict__ gives its key-value pairs. Serialized to JSON it produces [{"key":"...","value":"..."}].',
 'ai-sdk-test', 75),
('sap-ai',
 'What is ''model drift'' in MLOps?',
 '["Degradation of model performance over time as real-world data distribution shifts away from training data", "The model file moving between storage locations", "GPU temperature increase during training", "Training loss increasing during an epoch"]',
 0,
 'Model drift (concept drift) occurs when the statistical properties of input data change post-deployment, causing accuracy degradation that requires retraining.',
 'ai-mlops-test', 76),
('sap-ai',
 'What is a ''training pipeline'' in the MLOps context of SAP AI Core?',
 '["An automated, reproducible sequence of steps (data prep \u2192 training \u2192 evaluation \u2192 artifact registration) defined as an Argo Workflow", "A single Python training script", "A Jupyter notebook", "A CF buildpack"]',
 0,
 'Training pipelines encapsulate the full ML workflow as versioned, parameterized, and reproducible Argo Workflow steps that AI Core executes on demand.',
 'ai-mlops-test', 77),
('sap-ai',
 'How are training metrics (accuracy, loss) typically tracked in SAP AI Core training runs?',
 '["By writing metrics to the AI API metrics endpoint (POST /v2/lm/metrics) from within the training container", "Via TensorBoard connected to AI Core", "By logging to stdout only", "Through SAP Analytics Cloud"]',
 0,
 'Training containers call the AI API metrics endpoint during training to push key-value metrics, which are then viewable in AI Launchpad.',
 'ai-mlops-test', 78),
('sap-ai',
 'What is ''artifact lineage'' in SAP AI Core?',
 '["Tracking which dataset and executable produced which model artifact, creating a provenance chain", "A Git history of model code", "Versioning of Docker images", "Audit logs of API calls"]',
 0,
 'AI Core links artifacts (datasets, models) to the executions that produced them, enabling full traceability from raw data to deployed model.',
 'ai-mlops-test', 79),
('sap-ai',
 'In SAP AI Core, what is the purpose of ''labels'' on executions and deployments?',
 '["Key-value metadata for filtering and organizing runs in AI Launchpad", "Kubernetes pod labels", "Docker image tags", "Git commit references"]',
 0,
 'Labels are user-defined key-value pairs attached to AI Core objects, useful for filtering (e.g. by experiment, model version, or environment).',
 'ai-mlops-test', 80),
('sap-ai',
 'What does ''model registry'' provide in an MLOps workflow?',
 '["A versioned catalog of trained models with metadata (accuracy, training date, lineage) for promotion and deployment", "A Docker registry for model serving images", "A Git repository for model weights", "A SQL table of model names"]',
 0,
 'A model registry tracks all trained model versions, their metrics, and lineage, enabling governance processes like A/B testing, promotion to production, and rollback.',
 'ai-mlops-test', 81),
('sap-ai',
 'What is ''A/B testing'' of models in production?',
 '["Routing a percentage of real traffic to a new model version while the rest goes to the existing version, comparing performance", "Running two training jobs simultaneously", "Testing model A then model B sequentially", "Having two users test the model"]',
 0,
 'A/B testing routes live traffic (e.g. 10% to model B) to compare real-world performance metrics between model versions before full rollout.',
 'ai-mlops-test', 82),
('sap-ai',
 'What is the function of ''execution logs'' in SAP AI Core?',
 '["Stdout/stderr output from training containers, viewable via GET /v2/lm/executions/{id}/logs for debugging failed runs", "CPU utilization metrics", "API access logs", "Git commit history"]',
 0,
 'The AI API provides a logs endpoint for each execution, streaming container stdout/stderr so developers can debug training failures remotely.',
 'ai-mlops-test', 83),
('sap-ai',
 'In MLOps, what is ''continuous training'' (CT)?',
 '["Automatically retraining the model when new data arrives or drift is detected, keeping it current", "Training the model continuously for 24/7", "Running training on every API request", "Incremental training with gradient accumulation"]',
 0,
 'CT pipelines monitor data quality and model performance, triggering automated retraining workflows when thresholds are breached.',
 'ai-mlops-test', 84),
('sap-ai',
 'What is ''hyperparameter tuning'' and how is it typically done in SAP AI Core?',
 '["Searching for optimal model hyperparameters by running multiple executions with different parameter bindings (manual or automated)", "Tuning the GPU clock speed", "Adjusting API rate limits", "Modifying the Argo Workflow YAML parameters"]',
 0,
 'Hyperparameter tuning runs many training executions with varied parameter bindings (learning rate, batch size, etc.) and compares metrics to find the best configuration.',
 'ai-mlops-test', 85),
('sap-ai',
 'What is ''model explainability'' (XAI)?',
 '["Techniques (SHAP, LIME) that explain which features contributed to a model''s prediction", "The model''s documentation", "AI Core deployment logs", "The LLM''s reasoning trace in CoT"]',
 0,
 'XAI methods like SHAP values or LIME approximate feature contributions per prediction, helping stakeholders understand and trust model decisions.',
 'ai-mlops-test', 86),
('sap-ai',
 'What BTP service can be used alongside AI Core for scheduling recurring training pipeline runs?',
 '["SAP Job Scheduling Service", "SAP Event Mesh", "SAP Integration Suite", "CF Cron Service"]',
 0,
 'The SAP Job Scheduling Service on BTP allows you to schedule HTTP calls (e.g. triggering AI Core execution creation) on cron expressions.',
 'ai-btp-integration-test', 87),
('sap-ai',
 'How does a CAP application call a deployed AI Core model endpoint?',
 '["Via cds.connect.to pointing to a destination that routes to the AI Core deployment URL, or using the AI Core SDK directly", "By embedding the model in the CAP container", "Using CF service binding to AI Core", "Through SAP Integration Suite only"]',
 0,
 'CAP can use the Destination Service to configure the AI Core deployment URL and token, then call it via cds.connect.to or the node.js axios/fetch client.',
 'ai-btp-integration-test', 88),
('sap-ai',
 'What BTP service stores the AI Core service key credentials securely for use in apps?',
 '["SAP Credential Store or environment variables via CF service binding", "XSUAA only", "SAP Key Management Service", "BTP Secret Manager"]',
 0,
 'The SAP Credential Store or direct CF service binding (VCAP_SERVICES) securely provides AI Core credentials to BTP applications at runtime.',
 'ai-btp-integration-test', 89),
('sap-ai',
 'Which SAP BTP service can trigger an AI Core training run based on a file upload event?',
 '["SAP Event Mesh (publish event on upload \u2192 subscriber triggers run)", "SAP HANA Cloud trigger", "CF cron directly", "SAP Build Process Automation"]',
 0,
 'Event-driven architectures on BTP use Event Mesh: an app publishes an ''upload complete'' event, and a subscriber microservice calls the AI Core API to start a training execution.',
 'ai-btp-integration-test', 90),
('sap-ai',
 'In a BTP AI workflow, where are training datasets typically stored?',
 '["SAP HANA Cloud, AWS S3, Azure Blob Storage, or GCS \u2014 registered as Object Store artifacts in AI Core", "Inside the AI Core Kubernetes cluster storage", "In a CF file system", "In SAP Document Management Service"]',
 0,
 'Training data is stored in cloud object storage (S3/Blob/GCS). AI Core training containers access it via credentials registered as Object Store Secrets.',
 'ai-btp-integration-test', 91),
('sap-ai',
 'What SAP BTP service provides observability (logs and metrics) for AI Core deployments?',
 '["SAP Cloud Logging Service or SAP Dynatrace integration", "AI Core has no observability features", "SAP Analytics Cloud only", "CF Log Drain"]',
 0,
 'SAP Cloud Logging Service (or Dynatrace) can ingest AI Core deployment logs and custom metrics for end-to-end observability.',
 'ai-btp-integration-test', 92),
('sap-ai',
 'What is the ''SAP AI Business Services'' portfolio?',
 '["Pre-built AI microservices (Document Information Extraction, Business Entity Recognition, etc.) exposed as BTP services", "The AI Core management UI", "Custom ML models built by SAP customers", "The AI Core Python SDK"]',
 0,
 'SAP AI Business Services are ready-to-use AI APIs (document OCR, NLP entity extraction, translation) that require no ML expertise — just service binding and API calls.',
 'ai-btp-integration-test', 93),
('sap-ai',
 'What is ''Document Information Extraction'' (DOX) on BTP?',
 '["An AI service that extracts structured fields (vendor name, amount, date) from invoices and receipts using computer vision + NLP", "A PDF reader service", "A HANA text search function", "A CAP plugin for document management"]',
 0,
 'DOX uses ML models to classify documents and extract key fields, returning structured JSON — no custom training needed for standard document types.',
 'ai-btp-integration-test', 94),
('sap-ai',
 'How would you integrate a Gen AI Hub LLM call into a CAP service action?',
 '["In the action handler, use the AI Core Python/Node SDK or fetch() to POST to the deployment URL with an OAuth token", "Add @LLM annotation to the CDS action", "Use cf bind-service to attach the LLM", "Configure the LLM in mta.yaml"]',
 0,
 'CAP action handlers are regular Node.js/Python code; you call the AI Core deployment URL using fetch/axios with the OAuth token retrieved via client credentials.',
 'ai-btp-integration-test', 95),
('sap-ai',
 'What does this Python code do?

from gen_ai_hub.proxy.native.openai import init_models
models = init_models()
from openai import OpenAI
client = OpenAI(api_key=models[''gpt-4o''][''api_key''],
    base_url=models[''gpt-4o''][''base_url''])
response = client.chat.completions.create(
    model=''gpt-4o'', messages=[{''role'':''user'',''content'':''Hello''}])
print(response.choices[0].message.content)',
 '["Sends ''Hello'' to GPT-4o via SAP Gen AI Hub and prints the reply", "Trains a GPT-4o model", "Creates a Gen AI Hub deployment", "Lists available models"]',
 0,
 'init_models() retrieves AI Core deployment URLs and tokens; the OpenAI client is configured with them, routing all calls through SAP Gen AI Hub to GPT-4o.',
 'ai-sdk-test', 96),
('sap-ai',
 'What is ''function calling'' JSON and what does this schema define?

{
  "name": "get_product_price",
  "description": "Returns the current price of a product",
  "parameters": {
    "type": "object",
    "properties": {
      "product_id": {"type": "string", "description": "The product SKU"}
    },
    "required": ["product_id"]
  }
}',
 '["A tool definition telling the LLM it can call get_product_price with a product_id string parameter", "A REST API OpenAPI spec", "A CAP CDS action definition", "A Python function signature"]',
 0,
 'This is a function/tool definition for LLM function calling. The model decides when to invoke it and returns a structured call request with the argument values.',
 'ai-genai-hub-test', 97),
('sap-ai',
 'What does this RAG code snippet do?

from langchain_community.vectorstores import FAISS
from gen_ai_hub.proxy.langchain.openai import OpenAIEmbeddings

embedder = OpenAIEmbeddings(proxy_model_name=''text-embedding-ada-002'')
db = FAISS.from_documents(docs, embedder)
results = db.similarity_search(''How to create a CAP service?'', k=3)',
 '["Embeds ''docs'' using Ada-002 via Gen AI Hub, stores in FAISS, retrieves top 3 chunks similar to the query", "Trains a model on the documents", "Sends the documents to GPT-4", "Creates a SAP HANA vector store"]',
 0,
 'FAISS.from_documents calls the embedder (routed through Gen AI Hub) to embed all docs, builds an in-memory FAISS index, then similarity_search retrieves the top-3 matching chunks.',
 'ai-rag-test', 98),
('sap-ai',
 'In the SAP Orchestration Service, what is a ''module configuration''?',
 '["A JSON definition of which modules (LLM, templating, grounding, filtering) to include in the orchestration pipeline and their settings", "A Kubernetes ConfigMap", "A CAP service configuration", "An Argo Workflow step"]',
 0,
 'The orchestration pipeline is configured via a module_configurations JSON that lists each active module (llm_module, templating_module, grounding_module, etc.) with its parameters.',
 'ai-orchestration-test', 99),
('sap-ai',
 'What does this orchestration request accomplish?

{
  "orchestration_config": {
    "module_configurations": {
      "templating_module": {
        "grounding_response_identifier": "GROUND_RESULT",
        "template": [{"role":"system","content":"Answer using only: {{GROUND_RESULT}}"},
                     {"role":"user","content":"{{USER_QUERY}}"}]
      },
      "grounding_module": {"type":"document_grounding_service","filters":[{"collection_ids":["col-123"]}]},
      "llm_module": {"model_name":"gpt-4o","model_params":{"max_tokens":500}}
    }
  },
  "input_params": {"USER_QUERY": "What is SAP BTP?"}
}',
 '["Retrieves grounding context from collection col-123, injects it into the system prompt, then sends the user query to GPT-4o", "Runs a training pipeline", "Searches HANA Cloud directly", "Sends only the user query to GPT-4o with no context"]',
 0,
 'This orchestration call: (1) grounds by retrieving chunks from document collection col-123, (2) injects them as {{GROUND_RESULT}} in the system prompt, (3) calls GPT-4o with max 500 tokens output.',
 'ai-orchestration-test', 100),
('sap-ai',
 'What is ''fine-tuning'' an LLM and when should you prefer RAG instead?',
 '["Fine-tuning updates model weights on domain data (expensive, slow, needs retraining on updates); RAG injects context at runtime (cheaper, always current, no retraining needed)", "Fine-tuning is always better", "RAG updates model weights; fine-tuning retrieves documents", "Both are identical in cost and effort"]',
 0,
 'Fine-tuning bakes knowledge into weights — good for style/format. RAG is better for factual, frequently updated knowledge without retraining. Most enterprise use cases favor RAG.',
 'ai-rag-test', 101),
('sap-ai',
 'What is ''LLM output parsing'' and which LangChain component handles it?',
 '["Extracting structured data (JSON, lists) from free-text LLM responses using OutputParser classes", "Tokenizing the LLM input", "Truncating overly long responses", "Caching LLM outputs"]',
 0,
 'OutputParsers (e.g. PydanticOutputParser, JsonOutputParser) instruct the LLM to return structured format and parse the text response into Python objects.',
 'ai-sdk-test', 102),
('sap-ai',
 'What is ''prompt caching'' in the context of LLM APIs?',
 '["Reusing the computed key-value attention cache for repeated prompt prefixes, reducing latency and cost for identical context", "Storing responses in a Redis cache", "Saving prompts to a database", "Caching model weights in GPU memory"]',
 0,
 'Some LLM APIs (Anthropic) cache the attention states for static prompt prefixes (system message, long context), reducing compute cost for subsequent calls with the same prefix.',
 'ai-prompt-test', 103),
('sap-ai',
 'In SAP AI Core, what happens when an execution reaches ''DEAD'' status?',
 '["The execution failed and stopped; logs should be checked via the AI API logs endpoint for the error cause", "The execution completed successfully", "The execution is pending resource allocation", "The model was automatically retrained"]',
 0,
 'DEAD status indicates the execution failed (container crash, OOM, or pipeline error). Developers retrieve logs via GET /v2/lm/executions/{id}/logs to diagnose the issue.',
 'ai-mlops-test', 104),
('sap-ai',
 'Which of the following is true about SAP Generative AI Hub''s data privacy?',
 '["Prompts and responses are not used to train foundation models; data stays within SAP''s BTP infrastructure", "All prompts are shared with model providers for retraining", "User data is stored in model weights", "There are no data privacy guarantees"]',
 0,
 'SAP contractually ensures that data sent through Generative AI Hub (prompts/responses) is not used for training foundation models, maintaining enterprise data privacy.',
 'ai-genai-hub-test', 105),
('sap-ai',
 'What is ''top-k sampling'' in LLM generation?',
 '["Restricting token selection to the k most probable next tokens at each step", "Selecting the k longest responses", "Using k different models and averaging", "Limiting context to k tokens"]',
 0,
 'Top-k sampling keeps only the k highest-probability tokens in the distribution and samples from them, balancing quality and diversity.',
 'ai-genai-hub-test', 106),
('sap-ai',
 'What does ''stop sequence'' do in an LLM API call?',
 '["Tells the model to stop generating as soon as it produces one of the specified strings", "Sets the maximum tokens", "Defines the end of the system message", "Stops the deployment"]',
 0,
 'stop sequences (e.g. [''\n\n'', ''END'']) cause the model to halt generation immediately when it produces a matching string, useful for structured output.',
 'ai-genai-hub-test', 107),
('sap-ai',
 'What is ''logprobs'' in an LLM API response?',
 '["Log probabilities of the generated tokens, useful for uncertainty estimation and scoring", "Log files from the LLM server", "Profiling data for the model", "The model''s internal training logs"]',
 0,
 'logprobs returns the log-probability of each generated token, enabling applications to assess model confidence or rank multiple completions.',
 'ai-genai-hub-test', 108),
('sap-ai',
 'In the OpenAI API, what is the ''n'' parameter?',
 '["Number of completion choices to generate for each prompt", "Temperature multiplier", "Context window size", "Number of retry attempts"]',
 0,
 'n=3 returns 3 independent completions for the same prompt, useful for generating candidate responses and letting downstream logic choose the best.',
 'ai-genai-hub-test', 109),
('sap-ai',
 'What is ''structured output'' (JSON mode) in an LLM API?',
 '["Forcing the model to return valid JSON by setting response_format: { type: ''json_object'' }", "Formatting the prompt as JSON", "Returning token probabilities as JSON", "A specific model variant"]',
 0,
 'JSON mode constrains the model''s output to be valid JSON, ensuring downstream code can parse it reliably without wrapping in try/catch.',
 'ai-genai-hub-test', 110),
('sap-ai',
 'What does ''system fingerprint'' in an OpenAI API response indicate?',
 '["An identifier for the backend configuration used, which can affect determinism of outputs", "A security signature of the response", "The model version hash", "The API key fingerprint"]',
 0,
 'system_fingerprint tracks the server-side model configuration; the same prompt with the same seed but different fingerprints may produce different outputs.',
 'ai-genai-hub-test', 111),
('sap-ai',
 'What is ''token budget'' management in production LLM applications?',
 '["Tracking and limiting prompt + completion token usage per user/session to control API costs", "Setting a spending limit on a credit card", "Allocating GPU memory", "Configuring max_tokens only"]',
 0,
 'Token budget management monitors cumulative token usage, implements per-user quotas, and truncates or summarizes context to stay within cost and context limits.',
 'ai-genai-hub-test', 112),
('sap-ai',
 'What is a ''multi-modal'' LLM?',
 '["A model that processes multiple input types (text, images, audio) in addition to generating text", "A model running on multiple GPUs", "An ensemble of multiple LLMs", "A model supporting multiple languages"]',
 0,
 'Multi-modal models (e.g. GPT-4V, Gemini) accept images, documents, or audio as input alongside text, enabling visual QA and document understanding.',
 'ai-genai-hub-test', 113),
('sap-ai',
 'What is ''self-consistency'' prompting?',
 '["Generating multiple CoT reasoning paths and selecting the most common answer, improving accuracy", "Asking the model to check its own work once", "Using a consistent prompt template", "Sampling with temperature=0"]',
 0,
 'Self-consistency samples multiple reasoning chains (high temperature) and majority-votes the final answer, significantly improving complex reasoning accuracy over single-pass CoT.',
 'ai-prompt-test', 114),
('sap-ai',
 'What is ''ReAct'' prompting?',
 '["Interleaving Reasoning and Acting steps, where the model thinks, then calls a tool, then observes the result, repeating until done", "A prompt that makes the model react to user emotion", "A template for reactive UI generation", "A method for training reactive models"]',
 0,
 'ReAct (Reason + Act) enables LLM agents to alternate between reasoning (''I need to search X'') and tool actions (''Search: X'') using observation feedback in a loop.',
 'ai-prompt-test', 115),
('sap-ai',
 'What is ''Constitutional AI'' and how does it relate to prompt engineering?',
 '["A technique where the AI critiques and revises its own outputs against a set of principles, reducing harmful content", "A method of constitutional law analysis", "Fine-tuning on legal documents", "A UI for setting model rules"]',
 0,
 'Constitutional AI (from Anthropic) uses a set of principles to guide the model''s self-critique and revision, instilling values without human labeling of every example.',
 'ai-prompt-test', 116),
('sap-ai',
 'What is ''Tree of Thought'' (ToT) prompting?',
 '["Exploring multiple reasoning branches like a tree, evaluating intermediate thoughts and backtracking if needed", "A hierarchical data structure in prompts", "A prompt that lists thoughts as a tree diagram", "A method to reduce hallucinations by branching"]',
 0,
 'ToT extends CoT by exploring multiple reasoning paths in parallel, evaluating each intermediate step, and backtracking dead ends — useful for complex planning tasks.',
 'ai-prompt-test', 117),
('sap-ai',
 'What is ''RLHF'' (Reinforcement Learning from Human Feedback)?',
 '["A training technique that fine-tunes LLMs using human preference rankings to align model outputs with human values", "A method of reinforcing successful API calls", "A retrieval technique for LLMs", "A hyperparameter tuning method"]',
 0,
 'RLHF trains a reward model on human preference pairs, then fine-tunes the LLM with RL to maximize that reward, producing more helpful and harmless outputs (used in GPT-4, Claude).',
 'ai-mlops-test', 118),
('sap-ai',
 'What is ''document metadata filtering'' in RAG?',
 '["Pre-filtering vector search results by metadata (e.g. document_type=''invoice'', date>''2024-01-01'') before similarity ranking", "Removing metadata from documents before embedding", "Filtering out short documents", "Excluding documents with low embedding scores"]',
 0,
 'Metadata filtering combines structural constraints with semantic search, retrieving only chunks that meet both similarity and attribute criteria for more precise RAG.',
 'ai-rag-test', 119),
('sap-ai',
 'What is ''multi-vector retrieval''?',
 '["Generating multiple embeddings per document (summary + propositions + full text) to improve retrieval coverage", "Using multiple embedding models simultaneously", "Storing vectors in multiple databases", "Retrieving vectors from multiple tenants"]',
 0,
 'Multi-vector techniques embed different representations (summary, hypothetical questions, key propositions) of each chunk, increasing the chance of matching diverse query formulations.',
 'ai-rag-test', 120),
('sap-ai',
 'What is ''hypothetical document embedding'' (HyDE)?',
 '["Generating a hypothetical answer to the query with the LLM, then embedding that answer for retrieval instead of the raw query", "Creating fake documents for testing", "An embedding compression technique", "Generating synthetic training data"]',
 0,
 'HyDE improves RAG by asking the LLM to generate a hypothetical ideal document for the query, then using its embedding for similarity search — bridging the query-document gap.',
 'ai-rag-test', 121),
('sap-ai',
 'In LangChain, what is a ''Retriever'' object?',
 '["An abstraction that accepts a query string and returns relevant Document objects from any backing store (vector DB, SQL, web)", "A class for fetching web pages", "A Python iterator over training data", "An OData query builder"]',
 0,
 'LangChain Retrievers have a single interface (get_relevant_documents) and can wrap FAISS, Chroma, HANA Cloud, Pinecone, or custom retrieval logic.',
 'ai-sdk-test', 122),
('sap-ai',
 'What is ''ColBERT'' style retrieval?',
 '["Late interaction retrieval that stores per-token embeddings and scores query-document pairs at retrieval time for higher accuracy", "A BM25 variant", "A document summarization model", "A fine-tuned BERT for SAP data"]',
 0,
 'ColBERT keeps token-level embeddings for both query and document and computes MaxSim interaction scores at query time, offering accuracy between bi-encoders and cross-encoders.',
 'ai-rag-test', 123),
('sap-ai',
 'What HANA Cloud SQL stores and queries a vector embedding?

CREATE TABLE doc_chunks (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  content NCLOB,
  embedding REAL_VECTOR(1536)
);
SELECT TOP 5 id, content
FROM doc_chunks
ORDER BY COSINE_SIMILARITY(embedding, TO_REAL_VECTOR(?)) DESC;',
 '["Creates a table with a 1536-dim embedding column and retrieves the 5 most similar chunks to a query vector", "Deletes all chunks with low similarity", "Updates embeddings in the table", "Creates a HANA Calculation View over doc_chunks"]',
 0,
 'REAL_VECTOR(1536) stores 1536-dimensional embeddings (matching Ada-002 output). COSINE_SIMILARITY with ORDER BY DESC + TOP 5 returns the nearest neighbors.',
 'ai-rag-test', 124),
('sap-ai',
 'What is ''shadow deployment'' in MLOps?',
 '["Running a new model in parallel with the production model, receiving the same traffic but not returning responses \u2014 used for performance testing", "Deploying to a hidden environment", "Running models at night only", "A backup deployment activated on failure"]',
 0,
 'Shadow deployments receive copies of real requests and generate responses for offline evaluation without affecting users, de-risking new model launches.',
 'ai-mlops-test', 125),
('sap-ai',
 'What is ''canary deployment'' for ML models?',
 '["Gradually rolling a new model to a small percentage of traffic, monitoring metrics before full rollout", "Deploying to a test environment only", "A colorful name for blue-green deployment", "Deploying all model versions simultaneously"]',
 0,
 'Canary deployments release to e.g. 5% of traffic, collecting real-world performance data before committing to a full rollout.',
 'ai-mlops-test', 126),
('sap-ai',
 'In SAP AI Core, what does the ''PENDING'' execution status mean?',
 '["The execution has been created but is waiting for resources (Kubernetes pods) to be allocated before starting", "The run completed but results are pending review", "An error occurred before starting", "The configuration is invalid"]',
 0,
 'PENDING indicates the Argo Workflow is queued; AI Core''s Kubernetes backend hasn''t yet scheduled the pods needed to run the pipeline steps.',
 'ai-mlops-test', 127),
('sap-ai',
 'What is the function of a ''serving framework'' like Triton Inference Server in AI Core deployments?',
 '["Provides a high-performance, multi-model serving engine that handles batching, GPU utilization, and protocol translation for model inference", "Trains models faster", "Provides a Python REPL for model testing", "Replaces Argo Workflows for serving"]',
 0,
 'NVIDIA Triton (and similar frameworks like TorchServe, BentoML) optimize throughput by batching requests, maximizing GPU usage, and exposing standard gRPC/HTTP inference APIs.',
 'ai-deployments-test', 128),
('sap-ai',
 'What Python library provides the ''Pipeline'' abstraction for common NLP tasks using pre-trained Hugging Face models?',
 '["transformers (from Hugging Face)", "scikit-learn", "spacy", "nltk"]',
 0,
 'The Hugging Face ''transformers'' library provides pipeline() for zero-code text classification, NER, summarization, translation, etc. using pre-trained models.',
 'ai-sdk-test', 129),
('sap-ai',
 'What is ''quantization'' in the context of LLM deployment?',
 '["Reducing model weight precision (e.g. FP32 \u2192 INT8) to decrease memory footprint and increase inference speed with minimal accuracy loss", "Measuring model quality", "Assigning priority to inference requests", "Compressing training data"]',
 0,
 'Quantization converts floating-point weights to lower-bit integers, making large models fit on fewer GPUs and serving faster — widely used for edge/cost-optimized deployments.',
 'ai-deployments-test', 130),
('sap-ai',
 'What does this LangChain code create?

from langchain.chains import RetrievalQA
from gen_ai_hub.proxy.langchain.openai import ChatOpenAI

qa_chain = RetrievalQA.from_chain_type(
    llm=ChatOpenAI(proxy_model_name=''gpt-4o''),
    chain_type=''stuff'',
    retriever=vector_store.as_retriever(search_kwargs={''k'': 4})
)',
 '["A RAG QA chain that retrieves 4 chunks from the vector store and stuffs them into GPT-4o''s context to answer questions", "A training pipeline for GPT-4o", "A simple GPT-4o chatbot without retrieval", "A document ingestion pipeline"]',
 0,
 'RetrievalQA combines a retriever (fetching top-4 chunks) with the LLM (GPT-4o via Gen AI Hub). ''stuff'' chain type concatenates all chunks into one prompt.',
 'ai-rag-test', 131),
('sap-ai',
 'What is ''LLM observability'' and which tools provide it?',
 '["Tracing, logging, and monitoring of LLM calls (token usage, latency, prompts, responses) using tools like Langfuse, LangSmith, or Dynatrace", "CF log drain for AI Core", "Model accuracy tracking only", "A Fiori app for monitoring prompts"]',
 0,
 'LLM observability captures every LLM call''s inputs, outputs, latency, and token cost for debugging, quality evaluation, and cost optimization.',
 'ai-mlops-test', 132),
('sap-ai',
 'What is ''evaluation'' (evals) in LLM application development?',
 '["Systematically testing LLM outputs against expected answers or rubrics to measure quality, accuracy, and regression", "A model accuracy metric during training only", "A UI for testing prompts manually", "A BTP service for LLM quality checks"]',
 0,
 'Evals define test cases (question → expected answer) and scoring criteria (exact match, LLM-as-judge, RAGAS metrics) to catch regressions when prompts or models change.',
 'ai-mlops-test', 133),
('sap-ai',
 'What is ''RAGAS'' in the context of RAG evaluation?',
 '["A framework for evaluating RAG pipelines on metrics like faithfulness, answer relevancy, context precision, and context recall", "A Python RAG library for building pipelines", "A HANA vector search algorithm", "A SAP AI evaluation service"]',
 0,
 'RAGAS (Retrieval Augmented Generation Assessment) provides automatic, LLM-based metrics for end-to-end RAG pipeline quality without requiring ground-truth labels for all metrics.',
 'ai-rag-test', 134),
('sap-ai',
 'What is ''knowledge graph RAG''?',
 '["Augmenting LLM responses with structured knowledge graph triples (entity \u2192 relation \u2192 entity) instead of or alongside vector search", "A RAG system that only uses Wikipedia", "Graph databases used instead of vector stores always", "A visualization of RAG pipelines"]',
 0,
 'Knowledge graph RAG retrieves structured facts (e.g. from SAP''s business knowledge graph) and combines them with semantic vector search for more precise, relationship-aware answers.',
 'ai-rag-test', 135),
('sap-ai',
 'In the SAP AI Orchestration Service, how is grounding configured for a document collection?',
 '["In the grounding_module section of the orchestration request, specifying the vector_store type and collection_ids", "In the prompt template as a hardcoded context string", "By pre-fetching chunks and inserting them manually", "Through an environment variable pointing to the vector store"]',
 0,
 'The grounding_module in the orchestration request JSON specifies the document_grounding_service type and lists collection_ids to retrieve from, all handled server-side by the orchestration engine.',
 'ai-orchestration-test', 136),
('sap-ai',
 'What does the following AI Core Argo Workflow step do?

- name: train-model
  template: train-template
  inputs:
    parameters:
      - name: epochs
        value: ''10''
    artifacts:
      - name: training-data
        path: /data',
 '["Runs the train-template container step with epochs=10 and mounts a training-data artifact to /data inside the container", "Deploys a model to AI Core", "Creates an embedding from training data", "Registers a model artifact"]',
 0,
 'Argo Workflow steps reference a template (the container/script to run) and pass parameter values and input artifacts (mounted as files) to configure the execution.',
 'ai-scenarios-test', 137),
('sap-ai',
 'What is ''model watermarking'' in AI governance?',
 '["Embedding imperceptible signals in model outputs to identify the source model, enabling IP protection and content attribution", "Adding a copyright footer to responses", "Encrypting model weights", "A training regularization technique"]',
 0,
 'Model watermarking embeds statistical patterns in generated text or images that are detectable by the model owner, helping track unauthorized model use or output misuse.',
 'ai-mlops-test', 138),
('sap-ai',
 'What is the purpose of SAP''s AI Ethics guidelines in the context of Generative AI Hub?',
 '["Ensuring AI systems are explainable, fair, robust, and privacy-preserving; governing responsible use of AI in SAP products", "Providing legal disclaimers only", "Restricting which models can be used", "Auditing API call logs"]',
 0,
 'SAP''s AI ethics principles (explainability, fairness, robustness, privacy) guide how Generative AI Hub models are selected, configured, and exposed to ensure responsible enterprise AI.',
 'ai-genai-hub-test', 139),
('sap-ai',
 'What is ''inference latency'' and how is it typically measured for deployed models?',
 '["The time from receiving a request to returning the first token (TTFT) and completing the full response (total latency), measured in milliseconds", "The training time per epoch", "The time to deploy a model", "GPU idle time"]',
 0,
 'TTFT (time-to-first-token) and total latency are the key serving SLO metrics. They depend on model size, hardware, quantization, batching strategy, and prompt/response length.',
 'ai-deployments-test', 140),
('sap-ai',
 'What is the ''AI Foundation'' layer in SAP''s AI strategy?',
 '["The horizontal BTP layer (AI Core, Generative AI Hub, AI Launchpad) that all SAP products and customer applications build on top of for AI capabilities", "A specific SAP model", "A training dataset provided by SAP", "The SAP Data Warehouse Cloud product"]',
 0,
 'SAP AI Foundation (AI Core + Gen AI Hub + HANA vector engine) provides the shared AI infrastructure layer that powers both SAP business AI features and custom customer AI apps.',
 'ai-btp-integration-test', 141),
('sap-ai',
 'What is ''semantic similarity search'' vs ''keyword search''?',
 '["Semantic search finds conceptually related results using embeddings even without exact keyword matches; keyword search matches exact terms", "Both are identical in results", "Keyword search uses ML; semantic search uses regex", "Semantic search is always slower"]',
 0,
 'Semantic search captures meaning (a query for ''car'' finds documents about ''automobile''); keyword search requires the exact term. Embeddings enable semantic search.',
 'ai-rag-test', 142),
('sap-ai',
 'Which AI Core artifact kind stores a trained model''s files?',
 '["MODEL", "DATASET", "CONFIG", "EXECUTABLE"]',
 0,
 'Artifacts with kind: MODEL reference the trained model files in object storage, linking them to the execution that produced them for lineage and serving.',
 'ai-scenarios-test', 143),
('sap-ai',
 'What is ''responsible AI'' in enterprise AI deployment?',
 '["Ensuring AI systems are fair, transparent, accountable, and privacy-preserving through governance processes and technical safeguards", "Using only open-source models", "Limiting AI to non-critical tasks", "Requiring human approval for every AI output"]',
 0,
 'Responsible AI encompasses bias detection, explainability, human oversight, data privacy, and compliance processes that govern how AI systems are developed and deployed.',
 'ai-genai-hub-test', 144),
('sap-ai',
 'What Python code creates a basic chatbot memory using LangChain''s ConversationBufferMemory with AI Core?',
 '["ConversationChain(llm=llm, memory=ConversationBufferMemory()) where llm is the Gen AI Hub proxy", "ChatOpenAI(memory=True)", "AICoreClient.memory.create()", "langchain.Memory(backend=''aicore'')"]',
 0,
 'LangChain''s ConversationChain wraps any LLM with ConversationBufferMemory, automatically prepending the conversation history to each new prompt.',
 'ai-sdk-test', 145),
('sap-ai',
 'What is the ''AI Core service plan'' called that supports generative AI workloads?',
 '["extended (or sap-internal for SAP use)", "basic", "free-tier", "standard"]',
 0,
 'The ''extended'' service plan for SAP AI Core enables generative AI features including access to the Generative AI Hub and larger resource quotas.',
 'ai-intro-test', 146),
('sap-ai',
 'In SAP Generative AI Hub, what is the ''model library''?',
 '["The catalog of available foundation models (GPT-4, Claude, Gemini, Mistral, etc.) accessible through AI Core deployments", "A local folder of model files", "A HANA table of model metadata", "A Python package of pre-trained models"]',
 0,
 'The Gen AI Hub model library lists all models SAP has made available via AI Core, with details on capabilities, pricing, and context windows.',
 'ai-genai-hub-test', 147),
('sap-ai',
 'What is ''batch inferencing'' in SAP AI Core?',
 '["Running predictions on a large dataset using a one-off execution (not a persistent deployment), cost-effectively processing offline workloads", "Real-time API inference", "Training a model in batches", "Running multiple deployments in parallel"]',
 0,
 'Batch inferencing uses AI Core executions (not deployments) to process large datasets offline, with the execution running a container that loads the model and scores all records.',
 'ai-deployments-test', 148),
('sap-ai',
 'What is the difference between ''embedding'' and ''fine-tuning'' an LLM for domain adaptation?',
 '["Embeddings add domain knowledge at inference time via RAG (no weight changes); fine-tuning permanently updates weights on domain data (requires retraining)", "Both update model weights", "Embeddings require GPU training; fine-tuning does not", "They are two names for the same technique"]',
 0,
 'RAG with embeddings is inference-time domain adaptation (cheap, updatable). Fine-tuning bakes knowledge into weights (expensive, requires retraining when data changes).',
 'ai-rag-test', 149),
('sap-ai',
 'What does this SAP AI Orchestration request module do?

"filtering_module": {
  "input": { "filters": [{ "type": "azure_content_safety", "threshold": "ALLOW_SAFE" }] },
  "output": { "filters": [{ "type": "azure_content_safety", "threshold": "ALLOW_SAFE" }] }
}',
 '["Screens both the user input and the LLM output for harmful content using Azure Content Safety, blocking unsafe content at both ends", "Translates content between languages", "Logs all prompts and responses", "Limits token count in input and output"]',
 0,
 'Content filtering in SAP Orchestration uses Azure Content Safety (or similar) to classify and block harmful input prompts and LLM responses before they reach users.',
 'ai-orchestration-test', 150);
