-- SAP BTP Extra Assessment Questions (order_num 61-150)
-- INSERT ONLY — do not truncate; append to existing 60 questions
INSERT INTO public.assessment_questions
  (course_id, question, options, correct_option, explanation, topic_slug, order_num)
VALUES
('sap-btp',
 'In CAP CDS, what keyword is used to mark a service entity as read-only?',
 '["@readonly", "@insertOnly", "@immutable", "@locked"]',
 0,
 'The @readonly annotation prevents create/update/delete operations on a CDS entity exposed via a service.',
 '3-crud-test', 61),
('sap-btp',
 'What does the following CDS snippet declare?

entity Orders : cuid, managed { ... }',
 '["An entity with auto-generated UUID key and managed timestamp fields", "An entity that extends the Orders table from SAP ERP", "A view over Orders with change tracking", "An abstract entity used only for composition"]',
 0,
 'The ''cuid'' aspect adds a UUID key field; ''managed'' adds createdAt, createdBy, modifiedAt, modifiedBy fields automatically.',
 '3-crud-test', 62),
('sap-btp',
 'Which HTTP method is used by OData V4 to perform a partial update of an entity?',
 '["PATCH", "PUT", "POST", "MERGE"]',
 0,
 'OData V4 uses PATCH for partial updates (only changed fields). PUT replaces the entire entity.',
 '3-crud-test', 63),
('sap-btp',
 'In an OData V4 $batch request, what content type is used for the multipart envelope?',
 '["multipart/mixed", "application/json", "application/atom+xml", "text/plain"]',
 0,
 'OData V4 batch requests use ''multipart/mixed'' as the content type with a boundary separating each individual request.',
 '3-crud-test', 64),
('sap-btp',
 'What is the purpose of the $expand query option in OData?',
 '["To inline related entities in a single response", "To filter results by a condition", "To sort the result set", "To limit the number of returned records"]',
 0,
 '$expand retrieves associated navigation property data inline, avoiding extra round-trips. E.g. Orders?$expand=Items.',
 '3-crud-test', 65),
('sap-btp',
 'What does the following CAP handler do?

this.before(''CREATE'', ''Orders'', async req => {
  if (!req.data.customerId) req.reject(400, ''customerId required'');
});',
 '["Validates that customerId is present before inserting an Order", "Adds a default customerId to every new Order", "Runs after an Order is created to notify the customer", "Prevents any Order creation for anonymous users"]',
 0,
 'The before-CREATE hook runs before persistence. req.reject aborts the operation with the given HTTP status and message.',
 '10-validation-test', 66),
('sap-btp',
 'In CAP Node.js, which method reads a single entity by its key from the database inside a handler?',
 '["SELECT.one.from(Entity).where({ID})", "Entity.find({ID})", "db.get(Entity, ID)", "cds.read(Entity, ID)"]',
 0,
 'SELECT.one.from(Entity).where({ID: req.params[0]}) is the idiomatic CDS QL pattern for fetching one record.',
 '5-cap-1-test', 67),
('sap-btp',
 'What does srv.emit() do in CAP compared to srv.send()?',
 '["emit fires an asynchronous event; send expects a response", "send fires an asynchronous event; emit expects a response", "Both are identical", "emit is for OData, send is for REST"]',
 0,
 'srv.emit() triggers an event asynchronously with no return value. srv.send() is a synchronous action/function call expecting a result.',
 '5-cap-1-test', 68),
('sap-btp',
 'In the following CAP CDS, what does ''Composition of many'' mean?

entity Orders { ...
  items : Composition of many OrderItems on items.order = $self;
}',
 '["OrderItems are deeply owned by Orders; deleting an Order cascades to its items", "OrderItems can exist independently of Orders", "OrderItems are a view of Orders", "Orders are child entities of OrderItems"]',
 0,
 'Composition implies deep ownership: the composed entities (items) cannot exist without the parent (Order) and cascading delete is applied.',
 '8-cap-ms-test', 69),
('sap-btp',
 'Which annotation tells CAP to generate a Fiori List Report with a specific line item set?',
 '["@UI.LineItem", "@UI.SelectionFields", "@UI.Chart", "@UI.HeaderInfo"]',
 0,
 '@UI.LineItem defines the columns shown in Fiori List Report table. @UI.SelectionFields defines filter bar fields.',
 '4-f4-test', 70),
('sap-btp',
 'What is the output of the following CDS query in CAP?

const result = await SELECT.from(Books).columns(''title'',''author'').limit(5);',
 '["An array of up to 5 objects with only title and author fields", "An array of all Books with all fields, paginated", "A single Book object", "An OData response envelope"]',
 0,
 'SELECT.from(Entity).columns(...).limit(N) returns up to N plain JS objects with only the specified columns projected.',
 '6-sqllite-test', 71),
('sap-btp',
 'In CAP, what is the role of ''cds.env.requires'' configuration?',
 '["Declares external service dependencies and their kind/credentials", "Lists the CDS models to compile", "Configures the HTTP server port", "Enables or disables authentication globally"]',
 0,
 'cds.env.requires maps service names to their kind (e.g. ''hana'', ''sqlite'') and credentials, driving how CAP connects to them.',
 '5-cap-1-test', 72),
('sap-btp',
 'What happens when you annotate a CAP action with @cds.odata.bindingParameter.collection: true?',
 '["The action is bound to a collection (bulk action)", "The action accepts no parameters", "The action is exposed as a function import", "The action is hidden from metadata"]',
 0,
 'Setting bindingParameter.collection: true makes the action available on a collection (e.g. POST /Entity/actionName) rather than on a single entity.',
 '5-cap-1-test', 73),
('sap-btp',
 'In SAP HANA Cloud, which SQL function generates a universally unique identifier?',
 '["SYSUUID", "NEWID()", "UUID()", "GEN_RANDOM_UUID()"]',
 0,
 'SYSUUID is the SAP HANA function that returns a UUID string. In CAP with HANA, the cuid aspect uses this function.',
 '6-sqllite-test', 74),
('sap-btp',
 'Which CAP Node.js built-in service handles persistence operations for HANA and SQLite?',
 '["cds.db (DatabaseService)", "cds.model", "cds.server", "cds.auth"]',
 0,
 'cds.db refers to the connected DatabaseService instance (HANA or SQLite adapter) that executes CDS QL statements.',
 '5-cap-1-test', 75),
('sap-btp',
 'Consider this code:

const { Books } = cds.entities(''my.bookshop'');
await INSERT.into(Books).entries({ title: "CAP Guide", stock: 10 });',
 '["Inserts a new Book row using CDS QL", "Deletes a Book with title CAP Guide", "Updates stock for all books", "Runs a SELECT and returns Books"]',
 0,
 'INSERT.into(Entity).entries({...}) is the CDS QL way to insert a record; it maps to an INSERT SQL statement at runtime.',
 '3-crud-test', 76),
('sap-btp',
 'What does the ''@mandatory'' annotation do in CDS?',
 '["Marks a field as required (non-null) and triggers frontend validation", "Creates a primary key field", "Makes the field read-only", "Indexes the field in the database"]',
 0,
 '@mandatory causes CAP to generate a not-null constraint and Fiori Elements to show the field as required in forms.',
 '10-validation-test', 77),
('sap-btp',
 'In xs-security.json, what is the purpose of the ''role-template'' section?',
 '["Defines role templates that group scopes for assignment to users", "Lists the services that consume XSUAA", "Configures the OAuth token expiry", "Specifies the tenant mode"]',
 0,
 'Role templates bundle scopes and can be instantiated as roles, which are then assigned to role collections and users in BTP cockpit.',
 '12-auth-test', 78),
('sap-btp',
 'Which grant type is used by a CAP backend application to call another service using its own identity (no user involved)?',
 '["client_credentials", "authorization_code", "password", "refresh_token"]',
 0,
 'The client_credentials grant type is used for machine-to-machine (M2M) calls where no user context is needed.',
 '12-auth-test', 79),
('sap-btp',
 'In CAP, how do you restrict an entity so only users with scope ''Admin'' can read it?',
 '["@requires: ''Admin'' annotation on the entity or service", "Set requiredScopes in package.json", "Configure roles in xs-app.json", "Use req.reject in a before-READ handler"]',
 0,
 'The @requires annotation in CDS service definitions is the declarative way to enforce scope-based access. CAP checks the JWT for the scope at runtime.',
 '12-auth-test', 80),
('sap-btp',
 'What does the ''xsappname'' field in xs-security.json represent?',
 '["The globally unique name of the XSUAA service instance used as a scope prefix", "The name of the Cloud Foundry app", "The BTP subaccount name", "The MTA module name"]',
 0,
 'xsappname is the unique identifier for the XSUAA instance. All scopes are prefixed with it: ''xsappname!t12345.scope''.',
 '12-auth-test', 81),
('sap-btp',
 'In xs-app.json, what does ''authenticationType: none'' mean for a route?',
 '["The route is accessible without a JWT token (public)", "XSUAA authentication is required", "Basic auth is used", "OAuth client credentials are used"]',
 0,
 'authenticationType: none bypasses JWT verification for that route, making it publicly accessible without login.',
 '14-approuter-test', 82),
('sap-btp',
 'Which environment variable must be set on the App Router to point it at the backend destination?',
 '["destinations", "VCAP_SERVICES", "XSUAA_SERVICE_NAME", "backend_url"]',
 0,
 'The ''destinations'' env var (or bound destination service) provides the App Router with backend URLs and auth configuration.',
 '14-approuter-test', 83),
('sap-btp',
 'What is ''token exchange'' in the context of App Router + Destination Service?',
 '["Swapping a user JWT for a principal-propagation token to call a backend on behalf of the user", "Generating a new client_credentials token", "Refreshing an expired OAuth token", "Converting a SAML assertion to an OAuth token"]',
 0,
 'Token exchange (principal propagation) lets the App Router get a token scoped to the backend service on behalf of the logged-in user.',
 '13-destination-test', 84),
('sap-btp',
 'In BTP Destination Service, what ''Authentication'' type is used to pass the user''s JWT to an S/4HANA backend?',
 '["OAuth2SAMLBearerAssertion", "BasicAuthentication", "NoAuthentication", "OAuth2ClientCredentials"]',
 0,
 'OAuth2SAMLBearerAssertion converts the user''s OAuth token to a SAML assertion for principal propagation into ABAP/S4 backends.',
 '13-destination-test', 85),
('sap-btp',
 'Where is the xs-app.json file placed in a CAP + App Router project?',
 '["In the approuter/ directory (or the module serving the App Router)", "In the root of the project", "Inside the srv/ folder", "Next to mta.yaml"]',
 0,
 'xs-app.json must be in the directory from which the App Router (@sap/approuter) is started, typically an ''approuter'' or ''app'' folder.',
 '14-approuter-test', 86),
('sap-btp',
 'In mta.yaml, what does ''type: nodejs'' in a module declaration tell the MTA deployer?',
 '["The module is a Node.js application to be pushed as a Cloud Foundry app", "The module is a HANA database artifact", "The module is a static HTML5 app", "The module is a Java Spring Boot service"]',
 0,
 'type: nodejs instructs the MTA deployer to push the module as a CF Node.js buildpack application.',
 '15-deploy-test', 87),
('sap-btp',
 'What command deploys an MTA archive (.mtar) to Cloud Foundry?',
 '["cf deploy <file>.mtar", "cf push <file>.mtar", "mta deploy <file>.mtar", "cf install <file>.mtar"]',
 0,
 '''cf deploy <file>.mtar'' uses the MTA CF plugin (cf deploy) to deploy a multi-target application archive to Cloud Foundry.',
 '15-deploy-test', 88),
('sap-btp',
 'Which command builds the MTA project into a deployable .mtar file?',
 '["mbt build", "cf build", "cds build --for production", "npm run deploy"]',
 0,
 'mbt build (MTA Build Tool) reads mta.yaml and packages all modules and resources into a deployable .mtar archive.',
 '15-deploy-test', 89),
('sap-btp',
 'In mta.yaml, how do you declare that a module requires a specific service instance?',
 '["Under the module''s ''requires'' list referencing the resource name", "Under ''provides'' section of the module", "In a separate bindings.yaml file", "Via cf bind-service command only"]',
 0,
 'Each module has a ''requires'' list where you reference resource names defined in the ''resources'' section, causing automatic service binding.',
 '15-deploy-test', 90),
('sap-btp',
 'What is the purpose of ''cds build --for hana'' before MTA deployment?',
 '["Compiles CDS models to HANA-specific .hdbcds/.hdbtable artifacts", "Runs unit tests against HANA", "Installs HANA client npm package", "Generates OData metadata XML for HANA"]',
 0,
 'cds build --for hana transforms CDS entity definitions into HANA database artifacts (.hdbtable, .hdbview) placed in the gen/db folder.',
 '15-deploy-test', 91),
('sap-btp',
 'In CAP + HANA deployment, which service type manages database schema migrations?',
 '["SAP HANA Deployer (HDI container service)", "Cloud Foundry PostgreSQL", "BTP Schema Migration Service", "HANA Cloud Central"]',
 0,
 'The HDI (HANA Deployment Infrastructure) container handles deploying and migrating .hdb artifacts generated by cds build.',
 '15-deploy-test', 92),
('sap-btp',
 'What does the ''health-check-type: http'' setting in CF manifest.yml do?',
 '["Verifies the app is healthy by calling an HTTP endpoint", "Checks if the process is running without an HTTP call", "Disables health checks", "Restarts the app on every request"]',
 0,
 'health-check-type: http makes CF call the health-check-http-endpoint (default /) to confirm the app started successfully.',
 '15-deploy-test', 93),
('sap-btp',
 'Which cf CLI command shows recent logs for a running Cloud Foundry application?',
 '["cf logs <app-name> --recent", "cf tail <app-name>", "cf show-logs <app-name>", "cf events <app-name>"]',
 0,
 '''cf logs <app-name> --recent'' retrieves the last buffered log lines. Without --recent it streams live logs.',
 '15-deploy-test', 94),
('sap-btp',
 'In CAP, how do you switch between SQLite (dev) and HANA (prod) without changing application code?',
 '["Using cds.env profile (cds.requires.[db].kind) \u2014 ''sqlite'' in dev, ''hana'' in production", "By manually editing all db queries", "Using feature flags in App Router", "By deploying two separate apps"]',
 0,
 'CAP profiles in package.json or .cdsrc.json set cds.requires.db.kind per environment, transparently switching adapters.',
 '6-sqllite-test', 95),
('sap-btp',
 'Which CDS query returns all Orders placed in the last 7 days?',
 '["SELECT.from(Orders).where(''createdAt >'', sevenDaysAgo)", "Orders.filter(o => o.createdAt > sevenDaysAgo)", "SELECT * FROM Orders WHERE createdAt > ?", "cds.db.query(''SELECT FROM Orders'')"]',
 0,
 'CDS QL SELECT.from(...).where() accepts a condition string or object, supporting date comparisons against JS Date values.',
 '6-sqllite-test', 96),
('sap-btp',
 'What does the ''@assert.range'' annotation enforce in CAP?',
 '["That a numeric or date field''s value falls within a specified range", "That a string matches a regex pattern", "That a field is unique in the table", "That the field is indexed"]',
 0,
 '@assert.range: [min, max] causes CAP to validate that the value is within the range before persistence, rejecting out-of-range values.',
 '10-validation-test', 97),
('sap-btp',
 'In SAP HANA Cloud, what is a ''Calculation View''?',
 '["A graphical or SQL-based virtual view that combines multiple tables with complex logic", "A table stored in columnar format", "A synonym for an HDI container", "An OData service generated from HANA tables"]',
 0,
 'Calculation Views are HANA''s native analytical artifacts for complex joins, aggregations, and hierarchies, executed in-memory.',
 '6-sqllite-test', 98),
('sap-btp',
 'How does CAP handle DB transactions across multiple operations?',
 '["Using cds.tx(req) to create a transaction context that rolls back on error", "Transactions are not supported in CAP", "Each INSERT is auto-committed", "Using CF transaction service"]',
 0,
 'cds.tx(req) or srv.tx(req) creates a transactional context; if the handler throws, CAP rolls back all changes automatically.',
 '5-cap-1-test', 99),
('sap-btp',
 'What is the difference between ''cds watch'' and ''cds run'' for local development?',
 '["cds watch auto-reloads on file changes; cds run starts once without watching", "Both are identical", "cds run watches files; cds watch does not", "cds watch only compiles CDS; cds run starts the server"]',
 0,
 'cds watch enables live reload during development. cds run starts the server once; changes require a manual restart.',
 '5-cap-1-test', 100),
('sap-btp',
 'Consider this CAP error handler:

this.on(''error'', (err, req) => {
  if (err.code === ''SQLITE_CONSTRAINT'') req.error(409, ''Duplicate entry'');
});',
 '["Catches a SQLite unique constraint violation and returns a 409 Conflict", "Prevents all errors from reaching the client", "Logs errors to SAP Alert Notification", "Retries the operation on constraint failure"]',
 0,
 'The ''error'' event handler intercepts service-level errors, letting you map DB-specific error codes to meaningful HTTP responses.',
 '10-validation-test', 101),
('sap-btp',
 'Which UI5 control is used to display hierarchical data in a tree structure?',
 '["sap.ui.table.TreeTable", "sap.m.List with TreeItem", "sap.m.Table with expand", "sap.ui.core.HierarchyNode"]',
 0,
 'sap.ui.table.TreeTable renders hierarchical (parent-child) data with expand/collapse rows in SAPUI5.',
 '1-ss-test', 102),
('sap-btp',
 'What does the Fiori ''@UI.SelectionFields'' annotation control?',
 '["Which fields appear in the filter bar of a List Report", "Which columns appear in the table", "The default sort order", "The page title"]',
 0,
 '@UI.SelectionFields lists the entity properties that should be shown as filter criteria in the Fiori List Report filter bar.',
 '4-f4-test', 103),
('sap-btp',
 'In SAPUI5 MVC, what is the role of the formatter function?',
 '["Transforms a model value to a display value in the view (e.g. date formatting, status text)", "Validates user input before saving", "Sends an OData request", "Routes to a different view"]',
 0,
 'Formatters are pure JS functions referenced in XML view bindings (e.g. formatter: ''.formatDate'') that convert raw data to display strings.',
 '1-ss-test', 104),
('sap-btp',
 'Which UI5 class provides the base for all custom UI5 controls?',
 '["sap.ui.core.Control", "sap.ui.core.Element", "sap.m.Button", "sap.ui.core.Component"]',
 0,
 'Custom UI5 controls extend sap.ui.core.Control, implementing a renderer method that generates the HTML DOM.',
 '1-ss-test', 105),
('sap-btp',
 'In Fiori Elements with CAP, what annotation enables inline creation of child items in an Object Page?',
 '["@UI.Facets with ReferenceFacet + @UI.LineItem", "@UI.CreateHidden: false", "@insertable: true only", "@UI.QuickViewFacets"]',
 0,
 'An Object Page sub-section backed by a composition uses @UI.LineItem for the table and supports inline row creation when @insertable is not restricted.',
 '4-f4-test', 106),
('sap-btp',
 'What does sap.ui.define() do in SAPUI5?',
 '["Declares a module with its dependencies using AMD-style module loading", "Creates a new UI5 control", "Registers a route in the router", "Initializes the UI5 framework"]',
 0,
 'sap.ui.define is UI5''s AMD-compatible module system, listing dependency paths and providing them as arguments to the factory function.',
 '1-ss-test', 107),
('sap-btp',
 'What is the purpose of the manifest.json ''sap.app.dataSources'' section?',
 '["Declares OData services (or other data sources) the app consumes, with their URI and metadata", "Lists the UI5 libraries used", "Configures the router navigation targets", "Stores app translations"]',
 0,
 'dataSources in manifest.json registers named OData/REST service URLs; these are referenced by models in sap.ui5.models.',
 '2-ms-test', 108),
('sap-btp',
 'What is ''multitenancy'' in the context of SAP BTP SaaS applications?',
 '["One application instance serves multiple customer tenants with data isolation", "Each customer gets a separate CF space", "Multiple apps share one database table", "Tenants are BTP subaccounts used for billing only"]',
 0,
 'Multitenancy allows a single deployed app to serve multiple tenants. CAP''s @sap/cds-mtxs provides tenant isolation via separate HDI containers.',
 '15-deploy-test', 109),
('sap-btp',
 'In CAP''s multitenancy setup, what does the ''mtx'' sidecar do?',
 '["Handles tenant onboarding/offboarding and schema upgrades per tenant", "Serves static UI5 resources", "Manages XSUAA token refresh", "Routes requests to the correct CF instance"]',
 0,
 'The @sap/cds-mtxs sidecar exposes endpoints for tenant subscribe/unsubscribe and runs HDI deployment per tenant during onboarding.',
 '15-deploy-test', 110),
('sap-btp',
 'Which BTP service provides managed message queuing for decoupled microservices?',
 '["SAP Event Mesh", "SAP Pub/Sub", "CF Message Bus", "BTP Kafka Service"]',
 0,
 'SAP Event Mesh is BTP''s managed messaging service supporting queues and topics for asynchronous event-driven communication between apps.',
 '2-ms-test', 111),
('sap-btp',
 'In CAP, how do you emit an event to SAP Event Mesh from a service handler?',
 '["await messaging.emit(''topic/path'', payload) after binding the SAP/messaging service", "Using fetch() to POST to Event Mesh REST API", "Via CF environment variable EVENTS_URL", "With cds.emit(''cloud-event'', payload)"]',
 0,
 'CAP''s messaging facade (cds.connect.to(''messaging'')) wraps Event Mesh; calling emit() publishes to the configured topic transparently.',
 '2-ms-test', 112),
('sap-btp',
 'What is the ''SAP Alert Notification Service'' used for on BTP?',
 '["Sending notifications (email, Slack, webhook) triggered by app or platform events", "Monitoring Fiori UI errors", "Managing CF quota alerts only", "Sending push notifications to mobile apps"]',
 0,
 'Alert Notification Service lets you define conditions (e.g. CF app crashes) and deliver notifications through multiple channels like email, Slack, or PagerDuty.',
 '15-deploy-test', 113),
('sap-btp',
 'What does the following MTA resource definition create?

resources:
  - name: my-db
    type: com.sap.xs.hdi-container',
 '["An HDI container (HANA DB schema) provisioned on SAP HANA Cloud", "A PostgreSQL database", "A CF user-provided service", "An S3-compatible object store"]',
 0,
 'type: com.sap.xs.hdi-container instructs the MTA deployer to provision an HDI container in the bound HANA Cloud instance.',
 '15-deploy-test', 114),
('sap-btp',
 'In CAP, what is the significance of ''draft'' support (@odata.draft.enabled)?',
 '["Allows users to save incomplete records and resume editing before activating", "Makes the entity read-only until admin activates it", "Enables offline sync for mobile apps", "Stores data only in browser localStorage"]',
 0,
 'Draft-enabled entities in Fiori Elements let users save in-progress edits server-side without creating committed records, supporting collaborative locking.',
 '9-cap-f4-test', 115),
('sap-btp',
 'What SAP BTP service is used for storing and serving HTML5 applications managed by BTP?',
 '["HTML5 Application Repository", "CF Static Buildpack", "BTP Web IDE", "Fiori Launchpad Service"]',
 0,
 'The HTML5 Application Repository stores UI5/Fiori app artifacts and serves them; App Router fetches them at runtime using the html5-apps-repo service.',
 '14-approuter-test', 116),
('sap-btp',
 'Which command uploads a UI5 app to the HTML5 Application Repository via MTA?',
 '["It is handled automatically by the MTA deployer when module type is ''html5''", "cf push --html5", "npm run upload-html5", "cf deploy --html5-only"]',
 0,
 'In mta.yaml, a module with type: html5 and build-result pointing to the dist folder is automatically deployed to the HTML5 repo by cf deploy.',
 '14-approuter-test', 117),
('sap-btp',
 'What is the purpose of the ''Workzone'' service on SAP BTP?',
 '["Provides a managed Fiori Launchpad for accessing BTP applications", "Manages Cloud Foundry orgs and spaces", "Stores design-time CDS models", "Handles OAuth token management"]',
 0,
 'SAP Build Work Zone (formerly Launchpad Service) provides a unified Fiori Launchpad shell where users access all their BTP apps.',
 '14-approuter-test', 118),
('sap-btp',
 'In CAP CDS, what is the difference between ''Association'' and ''Composition''?',
 '["Associations are independent references; Compositions imply deep ownership with cascading lifecycle", "Both are identical in behavior", "Composition is used for 1-to-1, Association for 1-to-many", "Associations cascade deletes; Compositions do not"]',
 0,
 'Association links to independently existing entities. Composition implies the child belongs to the parent — deletion of the parent cascades to children.',
 '8-cap-ms-test', 119),
('sap-btp',
 'Which CAP annotation prevents an entity from being deleted via OData?',
 '["@deletable: false", "@readonly", "@delete: false", "@UI.Hidden"]',
 0,
 '@deletable: false (or @Capabilities.DeleteRestrictions.Deletable: false) suppresses the DELETE method for that entity in the OData service.',
 '3-crud-test', 120),
('sap-btp',
 'What is the output format of ''cds compile --to edmx''?',
 '["OData V4 metadata XML ($metadata document)", "JSON model definition", "SQL DDL statements", "OpenAPI 3.0 specification"]',
 0,
 'cds compile --to edmx generates the EDMX (Entity Data Model XML) used as the $metadata document for OData V4 services.',
 '5-cap-1-test', 121),
('sap-btp',
 'In a CAP project, where do you place custom event handlers for the CatalogService?',
 '["In srv/cat-service.js (or .ts) alongside the .cds service definition", "In db/schema.cds", "In app/fiori-annotations.cds", "In package.json under ''cds.handlers''"]',
 0,
 'CAP automatically associates a .js file with the same base name as the .cds service file in the same folder as its implementation file.',
 '5-cap-1-test', 122),
('sap-btp',
 'What happens when you run ''cds deploy --to sqlite'' in a CAP project?',
 '["Creates/updates a local SQLite database file with the schema and sample data", "Deploys to SAP HANA Cloud", "Generates SQL migration files only", "Runs integration tests against SQLite"]',
 0,
 'cds deploy --to sqlite creates the SQLite DB file (default: db.sqlite), applies the schema, and optionally loads CSV fixture data.',
 '6-sqllite-test', 123),
('sap-btp',
 'In the following xs-app.json route, what does ''scope'' enforce?

{ "source": "^/api/(.*)", "target": "/api/$1", "destination": "backend", "scope": "$XSAPPNAME.read" }',
 '["Only users with the ''read'' scope in their JWT can access /api/* routes", "The route is public", "Only admin can access the route", "The destination requires basic auth"]',
 0,
 'The ''scope'' field in xs-app.json makes App Router check the user''s JWT for the listed scope before forwarding the request to the destination.',
 '14-approuter-test', 124),
('sap-btp',
 'What does ''cf scale <app> -i 3'' do?',
 '["Scales the app to 3 instances for horizontal scaling", "Sets the memory to 3GB", "Creates 3 separate apps", "Restarts the app 3 times"]',
 0,
 '''cf scale -i N'' adjusts the number of running instances. CF load-balances traffic across all healthy instances automatically.',
 '15-deploy-test', 125),
('sap-btp',
 'Which CAP feature automatically adds ''createdAt'', ''createdBy'', ''modifiedAt'', ''modifiedBy'' fields to an entity?',
 '["The ''managed'' aspect", "The ''cuid'' aspect", "The ''@audited'' annotation", "The ''temporal'' aspect"]',
 0,
 'Adding '': managed'' to an entity definition causes CAP to insert and update these four audit fields automatically on every write.',
 '5-cap-1-test', 126),
('sap-btp',
 'In UI5 freestyle, what is the ''Component.js'' file responsible for?',
 '["Initializing the app, creating the router, and loading the root view", "Defining OData models", "Rendering HTML directly", "Configuring XSUAA authentication"]',
 0,
 'Component.js is the entry point of a UI5 Component-based app: it declares metadata, initializes models defined in manifest.json, and creates the root view.',
 '1-ss-test', 127),
('sap-btp',
 'What does the CAP ''@Capabilities.FilterRestrictions.NonFilterableProperties'' annotation do?',
 '["Prevents specific fields from being used in $filter queries", "Makes all fields filterable", "Restricts sorting on those fields", "Hides the fields from $select"]',
 0,
 'NonFilterableProperties tells OData clients (and CAP) that those fields cannot be used in $filter, improving security and performance.',
 '11-filter-sort-test', 128),
('sap-btp',
 'What is the function of ''HDI'' (HANA Deployment Infrastructure) in BTP?',
 '["Manages versioned deployment of HANA DB objects (tables, views, procedures) with delta migration", "Provides a REST API gateway for HANA", "Handles HANA Cloud backups", "Monitors HANA query performance"]',
 0,
 'HDI maintains a schema''s DB objects as design-time artifacts, applying only the changed objects on each deployment — enabling safe, repeatable DB migrations.',
 '15-deploy-test', 129),
('sap-btp',
 'In the context of CAP remote services, what does cds.connect.to(''S4'') return?',
 '["A service proxy instance for calling the S/4HANA OData service defined in cds.requires", "An HTTP client for S/4HANA", "The CF service binding credentials", "An XSUAA token for S/4HANA"]',
 0,
 'cds.connect.to returns a CAP service proxy that wraps the remote OData/REST API, allowing you to use CDS QL or srv.send() against it.',
 '13-destination-test', 130),
('sap-btp',
 'Which SAP BTP service provides API lifecycle management (versioning, rate limiting, analytics)?',
 '["SAP API Management", "SAP Integration Suite", "SAP Event Mesh", "BTP Gateway Service"]',
 0,
 'SAP API Management (part of Integration Suite) provides a gateway for publishing, securing, throttling, and monitoring APIs.',
 '2-ms-test', 131),
('sap-btp',
 'In UI5, what is the difference between one-way and two-way data binding?',
 '["One-way: model \u2192 view only; Two-way: changes in view update the model and vice versa", "One-way is faster; two-way is for read-only data", "Two-way only works with JSON model", "One-way requires OData; two-way uses localStorage"]',
 0,
 'One-way binding propagates changes from model to view. Two-way binding also propagates user input back to the model, enabling live form editing.',
 '1-ss-test', 132),
('sap-btp',
 'What does ''srv.before'' vs ''srv.after'' handler mean in CAP?',
 '["before runs before the DB operation; after runs after the DB operation and result is available", "Both run at the same time", "after runs before the DB; before runs after", "before is for reads; after is for writes"]',
 0,
 'Lifecycle order: before → (DB operation) → on → after. ''after'' handlers receive the result and can modify it before sending to the client.',
 '5-cap-1-test', 133),
('sap-btp',
 'Which of the following is the correct way to add a custom HTTP header to a CAP outbound request to a remote service?',
 '["srv.send({ method:''GET'', path:''/...'', headers:{ ''x-custom'':''value'' } })", "srv.get(''/...'').header(''x-custom'',''value'')", "cds.headers.set(''x-custom'',''value'')", "fetch(url, { headers: {...} }) \u2014 CAP does not support headers"]',
 0,
 'srv.send() accepts a full request object including headers, which CAP forwards to the remote service alongside auth headers.',
 '13-destination-test', 134),
('sap-btp',
 'In CAP, what is the purpose of ''cds.plugins''?',
 '["Extending the CAP framework with reusable cross-cutting functionality (e.g. audit log, attachments)", "Listing npm packages in package.json", "Configuring Fiori Elements plugins", "Adding SAP UI5 libraries"]',
 0,
 'CAP plugins (e.g. @cap-js/audit-logging, @cap-js/attachments) hook into the CDS lifecycle and add capabilities without modifying app code.',
 '5-cap-1-test', 135),
('sap-btp',
 'What is ''service binding'' in Cloud Foundry?',
 '["Attaching a service instance to an app so its credentials are injected into VCAP_SERVICES at runtime", "Linking two CF apps directly", "Configuring environment variables manually", "Binding a domain to an app"]',
 0,
 'cf bind-service creates a service binding that injects the service credentials JSON into the VCAP_SERVICES environment variable inside the app container.',
 '15-deploy-test', 136),
('sap-btp',
 'Which annotation in CDS marks an entity field as a virtual field (not persisted in DB)?',
 '["@Core.Computed or ''virtual'' keyword", "@readonly", "@Capabilities.InsertRestrictions", "@assert.format"]',
 0,
 'The ''virtual'' keyword in CDS defines a field that exists in the service model but is excluded from all DB-level persistence and queries.',
 '5-cap-1-test', 137),
('sap-btp',
 'What is the SAP Cloud Application Programming Model''s ''mock authentication'' mode?',
 '["A development mode where cds.env.requires.auth.kind is set to ''mock'', accepting predefined test users without real XSUAA", "A security vulnerability", "A production authentication fallback", "A feature for mobile apps"]',
 0,
 'Mock auth (kind: ''mock'') lets developers test authorization roles locally without a real XSUAA tenant, using a list of mock users in package.json.',
 '12-auth-test', 138),
('sap-btp',
 'In SAPUI5, what is the ''ODataModel V4'' class used for?',
 '["The official SAPUI5 client for OData V4 services with change sets, batch requests, and binding-based data loading", "An older model for OData V2 only", "A plain REST HTTP client", "A local storage model"]',
 0,
 'sap.ui.model.odata.v4.ODataModel is the SAPUI5 OData V4 client, providing property/list bindings, operations, and batch request management.',
 '2-ms-test', 139),
('sap-btp',
 'What does the following CDS snippet define?

service AdminService @(requires:''admin'') { ... }',
 '["A service that requires callers to have the ''admin'' scope/role in their JWT", "A service accessible only from admin IP addresses", "A service that automatically logs all requests", "A read-only service for administrators"]',
 0,
 '@(requires:''admin'') on a service definition restricts all endpoints in that service to callers whose JWT contains the ''admin'' scope.',
 '12-auth-test', 140),
('sap-btp',
 'In CF, what does ''cf create-service'' do?',
 '["Provisions a new service instance of the specified service plan in the CF space", "Binds an existing service to an app", "Creates a user-provided service", "Deploys an MTA archive"]',
 0,
 'cf create-service <service> <plan> <name> provisions a managed service instance (e.g. HANA Cloud, XSUAA) in the current CF org/space.',
 '15-deploy-test', 141),
('sap-btp',
 'Which CAP Node.js method is used to register a custom action handler?',
 '["this.on(''actionName'', Entity, handler)", "this.action(''actionName'', handler)", "srv.register(''actionName'', handler)", "cds.action(''actionName'', handler)"]',
 0,
 'In a CAP service implementation, this.on(''actionName'', Entity, handler) registers the handler for the named OData action/function bound to the entity.',
 '5-cap-1-test', 142),
('sap-btp',
 'What is the purpose of ''srv.run'' vs event-loop based handlers in CAP?',
 '["srv.run is used to execute CDS QL statements directly; event handlers respond to OData/REST requests", "Both are identical", "srv.run starts the HTTP server", "srv.run is only for testing"]',
 0,
 'cds.run or srv.run executes a CDS QL query (SELECT/INSERT/UPDATE/DELETE) on the database service, separate from event-handling lifecycle hooks.',
 '5-cap-1-test', 143),
('sap-btp',
 'What does ''cds.env.production'' evaluate to?',
 '["true when NODE_ENV=production is set, enabling HANA bindings and disabling development features", "The production database URL", "The number of CF instances", "The SAP BTP region name"]',
 0,
 'CAP checks NODE_ENV === ''production'' (via cds.env.production) to switch behaviors like stricter auth checks, disabling mock services, and enabling HANA.',
 '5-cap-1-test', 144),
('sap-btp',
 'In SAPUI5 Fiori Elements, what is the ''ObjectPage'' floorplan used for?',
 '["Displaying detailed information about a single entity with sections, sub-sections, and editable fields", "Showing a list of all entities", "Displaying a chart dashboard", "Providing a wizard-style data entry flow"]',
 0,
 'The Object Page floorplan renders one entity''s full details (header, facets, sections) and supports view/edit modes for a selected record from a List Report.',
 '4-f4-test', 145),
('sap-btp',
 'What is the role of the ''tenant discriminator'' in CAP multitenancy?',
 '["A field/scope that routes each request to the correct tenant''s HDI container based on the JWT tenant ID", "A BTP subaccount billing field", "A HANA schema name prefix", "A CF organization identifier"]',
 0,
 'CAP''s MTX extension reads the tenant ID from the JWT and routes all DB operations to the corresponding HDI container, enforcing data isolation.',
 '15-deploy-test', 146),
('sap-btp',
 'Which SAP BTP service provides managed Redis caching for BTP applications?',
 '["SAP BTP Redis Hyperscaler Option (Object Store/Hyperscaler-managed Redis)", "SAP HANA Caching Layer", "CF Buildpack Cache", "BTP Memcache Service"]',
 0,
 'SAP BTP offers a hyperscaler-managed Redis service (via Object Store or a dedicated Redis plan) for session caching and application-level caching.',
 '2-ms-test', 147),
('sap-btp',
 'What does the following xs-app.json configuration do?

{ "welcomeFile": "/index.html", "authenticationMethod": "route" }',
 '["Serves index.html as the root and applies authentication per route (not globally)", "Makes all routes public", "Forces XSUAA login on every page load regardless of route", "Disables the App Router welcome page"]',
 0,
 'authenticationMethod: ''route'' means each route''s authenticationType setting governs auth individually, vs ''none'' which makes all routes public.',
 '14-approuter-test', 148),
('sap-btp',
 'In CAP, what is the ''csv'' folder used for in the db/ directory?',
 '["Stores .csv files that CAP auto-imports as seed data into the database during cds deploy", "Contains database migration scripts", "Holds exported OData responses", "Stores backup of HANA tables"]',
 0,
 'CAP automatically reads .csv files in db/data/ (or db/csv/) on cds deploy and populates the corresponding entities as initial data.',
 '6-sqllite-test', 149),
('sap-btp',
 'What does the ''@sap/cds-dk'' package provide?',
 '["The CAP development kit: cds CLI commands (cds watch, cds build, cds deploy, cds compile)", "The CAP runtime for production", "The HANA client driver", "The SAPUI5 tooling CLI"]',
 0,
 '@sap/cds-dk is the development kit installed globally (npm i -g @sap/cds-dk) that provides all cds CLI commands for scaffolding, building, and deploying CAP projects.',
 '5-cap-1-test', 150);
