-- SAP CAP (Cloud Application Programming Model) Assessment Questions
-- 70 questions across all 7 modules, order_num 4001-4070
-- Run AFTER sap_cap_seed.sql to ensure sap-cap course exists

INSERT INTO public.assessment_questions
  (course_id, question, options, correct_option, explanation, topic_slug, order_num)
VALUES

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 1: CAP Foundations (10 questions) — order_num 4001-4010
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'A developer new to SAP BTP wants to build a business service that exposes data via OData V4 and stores it in HANA Cloud. Which SAP framework is purpose-built for exactly this pattern?',
 '["SAP CAP (Cloud Application Programming Model)", "SAP Build Apps", "SAP Integration Suite", "ABAP RESTful Application Programming Model"]',
 0,
 'SAP CAP is designed precisely for building OData-exposing services backed by HANA Cloud (or SQLite for local dev), with CDS as the modelling language and Node.js or Java as runtimes.',
 'cap-01-what-is-cap', 4001),

('sap-cap',
 'You run `cds init my-project` and inspect the generated folder structure. Which file in the `db/` folder defines the domain entities your service will expose?',
 '["schema.cds — the CDS domain model file", "package.json — project manifest", "server.js — the Node.js entry point", "mta.yaml — the MTA deployment descriptor"]',
 0,
 'By convention, `db/schema.cds` is where CAP developers place entity definitions. The `db/` folder is for persistence-layer artefacts; `srv/` holds service definitions.',
 'cap-02-project-structure', 4002),

('sap-cap',
 'Which command starts the CAP development server locally, watches for file changes, and serves OData V4 endpoints?',
 '["cds watch", "cds run", "npm start", "cds serve --live"]',
 0,
 '`cds watch` is the standard CAP developer command. It starts the in-process SQLite database, applies pending migrations, and hot-reloads on every `.cds` or `.js` file change.',
 'cap-03-cds-cli', 4003),

('sap-cap',
 'In a CAP project, what is the purpose of the `cds.requires` section in `package.json`?',
 '["Declaring external service bindings and their kinds (e.g., database, messaging, auth)", "Listing npm production dependencies", "Specifying which Node.js version to use", "Defining OData annotation vocabularies"]',
 0,
 '`cds.requires` maps logical names (like `db`, `auth`, `messaging`) to their implementation kind and credentials. At runtime and at design time, CAP reads this to wire up the correct adapters.',
 'cap-04-cds-configuration', 4004),

('sap-cap',
 'During local development with `cds watch`, what database does CAP use by default, and why?',
 '["In-memory SQLite — it requires zero setup and is reset on each restart", "SAP HANA Cloud — to mirror production", "PostgreSQL — widely available on developer laptops", "SAP ASE — bundled with the CAP SDK"]',
 0,
 'CAP uses `@cap-js/sqlite` (in-memory or file-based) by default. It eliminates the need for a running database server during development, making onboarding fast.',
 'cap-05-local-development', 4005),

('sap-cap',
 'A CAP application in production must authenticate users via SAP BTP XSUAA. Which `cds.requires` entry enables this?',
 '["\"auth\": { \"kind\": \"xsuaa\" }", "\"security\": { \"type\": \"jwt\" }", "\"oauth\": { \"provider\": \"xsuaa\" }", "\"uaa\": { \"enabled\": true }"]',
 0,
 'Setting `cds.requires.auth.kind = "xsuaa"` instructs CAP to validate incoming JWT tokens issued by the XSUAA service bound to the app, enabling role-based access control.',
 'cap-04-cds-configuration', 4006),

('sap-cap',
 'What is the difference between `cds compile --to sql` and `cds deploy --to hana`?',
 '["compile generates DDL SQL; deploy executes it against a live database", "compile runs tests; deploy runs the app", "compile minifies CDS files; deploy uploads them to BTP", "They are synonymous — both generate and apply DDL"]',
 0,
 '`cds compile --to sql` outputs the SQL DDL as text (useful for review). `cds deploy --to hana` generates DDL *and* applies it to the configured HANA Cloud instance via HDI.',
 'cap-03-cds-cli', 4007),

('sap-cap',
 'You want to test your CAP OData service without writing any test code. Which built-in UI does CAP''s development server expose?',
 '["Fiori Elements preview at /$metadata and the service root", "Swagger UI at /swagger", "Apollo Studio at /graphql", "An embedded Postman at /test"]',
 0,
 'CAP serves the OData `$metadata` document and a Fiori Elements-compatible generic UI out of the box. Navigating to the service root also shows the entity set list.',
 'cap-05-local-development', 4008),

('sap-cap',
 'In the CAP programming model, what is CDS (Core Data Services)?',
 '["A domain-specific language for defining data models, services, and annotations in a database-agnostic way", "A SAP-proprietary JavaScript framework for building UIs", "An ABAP keyword for dictionary objects", "A set of REST API specifications"]',
 0,
 'CDS is CAP''s built-in DSL. It describes entities (data model), services (API surface), and annotations (UI hints, authorization) in `.cds` files that compile to SQL DDL, OData metadata, and more.',
 'cap-01-what-is-cap', 4009),

('sap-cap',
 'A teammate complains that after pulling the latest code, `cds watch` fails because the in-memory database is missing tables. What is the most likely fix?',
 '["Run `cds deploy --to sqlite` to build the local SQLite schema file", "Reinstall Node.js", "Delete package-lock.json and run npm install", "Set NODE_ENV=production"]',
 0,
 'When switching from in-memory to file-based SQLite (or after schema changes), running `cds deploy --to sqlite` generates/updates the `.db` file so `cds watch` can start with the correct schema.',
 'cap-05-local-development', 4010),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 2: CDS Modelling (12 questions) — order_num 4011-4022
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'You define two CDS entities: `Books` and `Authors`. Each Book has one Author, and each Author may have many Books. Which CDS association type correctly models this from the Books side?',
 '["Association to Authors", "Composition of Authors", "Association to many Authors", "Composition of many Authors"]',
 0,
 'A simple `Association to Authors` in `Books` represents a many-to-one relationship (many Books → one Author). Compositions are reserved for parent-child ownership where the child cannot exist independently.',
 'cap-11-associations', 4011),

('sap-cap',
 'What is the functional difference between `Composition` and `Association` in CDS?',
 '["Compositions imply ownership — child entities are deeply copied and deleted with the parent; associations do not", "Compositions generate a foreign key; associations generate a join table", "They are identical at the database level", "Compositions are for OData V4 only; associations work with all protocols"]',
 0,
 'CDS Compositions model a strict parent-child lifetime: deep insert, cascade update, and cascade delete are automatically handled by CAP. Associations are simple FK references with no ownership semantics.',
 'cap-11-associations', 4012),

('sap-cap',
 'Which CDS keyword makes an entity automatically include `createdAt`, `createdBy`, `modifiedAt`, and `modifiedBy` managed fields?',
 '["using { managed } from ''@sap/cds/common''", "annotate MyEntity with @managed", "aspect managed { ... } — must be defined manually", "Entity MyEntity extends cds.Managed"]',
 0,
 'The `managed` aspect from `@sap/cds/common` adds four audit fields. CAP automatically populates them on every INSERT and UPDATE without any custom handler code.',
 'cap-13-common-reuse', 4013),

('sap-cap',
 'You add `@readonly` to a CDS entity in a service definition. What effect does this have on the generated OData V4 capabilities?',
 '["Only GET operations are allowed; POST/PUT/PATCH/DELETE return 405 Method Not Allowed", "The entity is excluded from $metadata", "The entity can be read only by admin users", "All operations are allowed but audited"]',
 0,
 '`@readonly` suppresses write capabilities in the OData metadata (InsertRestrictions, UpdateRestrictions, DeleteRestrictions set to false). CAP enforces this at the framework level before hitting any handler.',
 'cap-20-annotations-fiori', 4014),

('sap-cap',
 'A CDS view uses the `where` clause with a session variable: `where UserID = $user.id`. What CAP feature powers this?',
 '["Instance-based authorization using CDS views that filter by the current user context automatically", "A SQL WHERE clause passed as a query parameter", "A JavaScript handler that injects the user ID", "An XSUAA scope check on the entity"]',
 0,
 'CAP supports parameterized CDS views and access control rules using `$user` pseudo-variables. This enables row-level security directly in the data model layer.',
 'cap-17-instance-auth', 4015),

('sap-cap',
 'Which CDS construct allows you to reuse a set of elements across multiple entities without creating a database inheritance relationship?',
 '["aspect — a named set of elements mixed into entities with `:`", "abstract entity — not mapped to a DB table", "type — an alias for a primitive or structured type", "service — groups entities for exposure"]',
 0,
 '`aspect` in CDS is a reuse mixin. When an entity uses `: MyAspect`, the aspect''s elements are included in the entity''s structure and table. No extra table or join is generated.',
 'cap-13-common-reuse', 4016),

('sap-cap',
 'You want a CDS entity to have a UUID primary key auto-generated by CAP on insert. Which definition is correct?',
 '["key ID : UUID; annotated with @cds.on.insert: {= generate uuid}", "key ID : Integer @cds.auto.increment", "key ID : String(36) @autogenerate", "key ID : UUID @default: uuid()"]',
 0,
 'In practice you declare `key ID : UUID;` and CAP generates it automatically on INSERT because UUID keys get auto-generated by the framework. The explicit annotation `@cds.on.insert` is optional but documents the intent.',
 'cap-10-entities-types', 4017),

('sap-cap',
 'What is the purpose of `@sap/cds/common` in CDS models?',
 '["It provides reusable types and aspects like managed, Currency, Country, Language, and common code list patterns", "It contains the OData V4 protocol implementation", "It is the npm package for the CAP runtime", "It defines the HDI deployment plugin"]',
 0,
 '`@sap/cds/common` ships with the CDS toolkit and provides standardised reuse types (Currency, Language, Country) and aspects (managed, cuid) that align with SAP data model conventions.',
 'cap-13-common-reuse', 4018),

('sap-cap',
 'In a CDS service definition, what does `as projection on db.Books` accomplish compared to directly exposing `db.Books`?',
 '["A projection creates a view over the entity, allowing you to rename, hide, or add calculated elements without altering the database table", "A projection creates a separate database table", "A projection enables caching of query results", "A projection is identical to exposing the entity directly"]',
 0,
 'Projections are virtual views in the service layer. They let you control which fields are exposed, rename columns for the API consumer, and add virtual/calculated elements — all without changing the DB schema.',
 'cap-14-projections-views', 4019),

('sap-cap',
 'Your CDS model has `entity Orders { ... items : Composition of many OrderItems on items.order = $self; }`. When a client sends a deep-insert (POST with nested items), what does CAP do automatically?',
 '["Inserts the Order and all nested OrderItems in a single transaction, rolling back everything if any step fails", "Inserts only the Order; items must be POSTed separately", "Creates a batch request that the client must confirm", "Throws an error because nested inserts are not supported"]',
 0,
 'CAP''s Composition of many triggers automatic deep-insert handling. The entire parent + children graph is inserted atomically, and CAP generates the FK on each child automatically.',
 'cap-11-associations', 4020),

('sap-cap',
 'You need an OData Navigation Property from `Orders` to `Customer`. The navigation should NOT cascade-delete the customer when the order is deleted. Which CDS construct is correct?',
 '["order.customer : Association to Customers", "order.customer : Composition of Customers", "order.customer : Association to many Customers", "order.customer : ManyToOne(Customers)"]',
 0,
 'A simple `Association to Customers` creates a navigation property without ownership semantics. Composition would imply that deleting an Order deletes its Customer — which is incorrect for shared reference data.',
 'cap-11-associations', 4021),

('sap-cap',
 'Which CDS annotation enables automatic Fiori List Report page generation for an entity when viewed in SAP Build Work Zone?',
 '["@UI.LineItem — defines which columns appear in list reports", "@odata.publish: true", "@Fiori.Enable: true", "@SAP.List"]',
 0,
 '`@UI.LineItem` tells Fiori Elements which fields to display in the list table. Combined with `@UI.SelectionFields` for filters, it''s the minimum needed to render a working List Report without custom code.',
 'cap-20-annotations-fiori', 4022),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 3: Service Development (10 questions) — order_num 4023-4032
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'You want custom logic to run before a new Order is created. In which CAP event handler do you place this validation code?',
 '["srv.before(''CREATE'', ''Orders'', handler)", "srv.on(''CREATE'', ''Orders'', handler)", "srv.after(''CREATE'', ''Orders'', handler)", "srv.validate(''Orders'', handler)"]',
 0,
 '`before` handlers run before CAP''s generic processing. This is the right place for input validation, authorization checks, or enrichment that must happen before the INSERT reaches the database.',
 'cap-24-custom-handlers', 4023),

('sap-cap',
 'In a CAP `srv.on` handler for READ, what must you do at the end to pass the result to the framework?',
 '["Return the result (or call next()) — CAP uses the return value or the resolved Promise", "Call req.send(data)", "Call res.json(data)", "Emit a ''done'' event"]',
 0,
 'CAP handlers use a middleware-like pattern. Returning a value (or a resolved Promise) from an `on` handler signals CAP to use that as the response. Calling `next()` delegates to the next registered handler.',
 'cap-24-custom-handlers', 4024),

('sap-cap',
 'A CAP service defines a custom action: `action submitOrder(orderID: UUID) returns Order`. How is this exposed in OData V4?',
 '["As a bound or unbound OData Action with a POST request to /submitOrder", "As an OData Function with a GET request", "As a PATCH to the Orders entity", "Actions are not supported in OData V4; use Function Imports instead"]',
 0,
 'CAP exposes CDS `action` definitions as OData V4 Actions (POST-based, may have side effects). CDS `function` definitions become OData V4 Functions (GET-based, side-effect free). Both are first-class in OData V4.',
 'cap-25-actions-functions', 4025),

('sap-cap',
 'You need to call an external REST API from a CAP service handler. Which CAP approach is recommended for consuming external OData services?',
 '["Import the external service in CDS with `using ExternalService from ''./external/ExternalService.csn''` and use `cds.connect.to`", "Use axios directly in the handler", "Use SAP Integration Suite always", "Declare it in cds.requires and use the generated client via cds.connect.to(''ExternalService'')"]',
 3,
 'The canonical CAP way is to declare the external service in `cds.requires`, import its EDMX/CSN, and consume it via `cds.connect.to(''ServiceName'')`. CAP then handles protocol, binding, and mocking automatically.',
 'cap-28-external-services', 4026),

('sap-cap',
 'What is the purpose of `req.error()` vs `req.reject()` in a CAP handler?',
 '["req.error() collects multiple errors and continues; req.reject() immediately aborts with a single error", "req.error() logs to console; req.reject() sends an HTTP error", "They are identical", "req.error() is for validation; req.reject() is for authorization failures"]',
 0,
 '`req.error()` accumulates errors that are all returned together (useful for field-level validation showing multiple issues). `req.reject()` immediately terminates the request with a single error and HTTP status.',
 'cap-24-custom-handlers', 4027),

('sap-cap',
 'You want a CAP service to send a CloudEvent to SAP Event Mesh when an order is confirmed. Which API do you use?',
 '["const messaging = await cds.connect.to(''messaging''); messaging.emit(''OrderConfirmed'', payload)", "require(''@sap/xb-msg'').emit()", "fetch(messagingURL, { method: ''POST'', body: payload })", "cds.emit(''OrderConfirmed'', payload)"]',
 0,
 'CAP has a built-in messaging adapter. Connecting via `cds.connect.to(''messaging'')` (with Event Mesh configured in `cds.requires`) and calling `.emit()` handles serialisation, protocol, and credentials automatically.',
 'cap-29-messaging', 4028),

('sap-cap',
 'A CAP handler calls `SELECT.from(Books).where({ author_ID: authorId })`. At which layer does this query execute?',
 '["The CAP query API constructs a CQN object; the database service translates it to SQL and executes against the connected DB", "It executes as a raw SQL string directly", "It triggers an OData GET request to an external service", "It is translated to SPARQL for the graph database"]',
 0,
 'CAP uses CQN (Core Query Notation) — a JSON-like query representation. The database service (SQLite, HANA) receives the CQN and converts it to the appropriate SQL dialect. This keeps handler code DB-agnostic.',
 'cap-23-querying-cqn', 4029),

('sap-cap',
 'In a CAP application, what is the `cds.tx()` API used for?',
 '["Opening an explicit database transaction so multiple DB operations are atomic, with commit() and rollback()", "Sending a transactional email", "Creating a multi-part HTTP request", "Connecting to SAP Transaction Manager"]',
 0,
 '`cds.tx()` gives you an explicit transaction context. All DB operations within the callback share the same ACID transaction — if any fails, `cds.tx()` automatically rolls back. CAP otherwise manages transactions per request automatically.',
 'cap-23-querying-cqn', 4030),

('sap-cap',
 'You want to extend a CAP service from a different package (plugin pattern) without modifying the original service file. Which CDS keyword enables this?',
 '["extend service CatalogService with { ... }", "override service CatalogService { ... }", "plugin service CatalogService { ... }", "merge service CatalogService { ... }"]',
 0,
 '`extend` is CDS''s open/closed mechanism. Extensions can add entities, actions, and annotations to an existing service from a separate `.cds` file or package — the original service file is untouched.',
 'cap-26-service-extensions', 4031),

('sap-cap',
 'A customer reports that changing one Order''s status triggers a read of all Orders. You suspect the issue is in a CAP `after READ` handler. What is the most efficient fix?',
 '["Check req.query or req.params — process only the entities returned in the current result, not a new SELECT * from Orders", "Move the logic to a before handler", "Disable the after handler", "Add an index to the Orders table"]',
 0,
 '`after READ` handlers receive the result set of the *current* query. Re-querying all Orders inside it causes N+1 problems. The correct approach is to work with the data already in `req.data` or the `results` parameter.',
 'cap-24-custom-handlers', 4032),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 4: Persistence & HANA Cloud (10 questions) — order_num 4033-4042
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'Your CAP application uses HANA Cloud in production. What does HDI (HANA Deployment Infrastructure) do?',
 '["HDI manages schema evolution — it deploys, updates, and tracks CDS-generated DDL artefacts into a HANA container with full lifecycle management", "HDI is a SAP HANA indexing algorithm", "HDI replaces XSUAA for authentication in HANA", "HDI is a monitoring dashboard for HANA Cloud"]',
 0,
 'HDI provides a container-based approach to HANA schema deployment. CAP generates `.hdbtable`, `.hdbview`, and other design-time artefacts; HDI applies them to the container, handling delta migrations automatically.',
 'cap-35-hana-cloud', 4033),

('sap-cap',
 'Which npm package do you add to a CAP Node.js project to switch from SQLite to HANA Cloud?',
 '["@cap-js/hana — the official CAP HANA adapter replacing the older hdb/hana-client approach", "@sap/hana-client directly in server.js", "pg — PostgreSQL driver (HANA uses the same protocol)", "knex — a query builder that works with all DBs"]',
 0,
 '`@cap-js/hana` is the modern CAP HANA adapter. Adding it and setting `cds.requires.db.kind = "hana"` with the correct credentials is all that''s needed to point CAP at HANA Cloud.',
 'cap-35-hana-cloud', 4034),

('sap-cap',
 'A CDS entity is annotated with `@cds.persistence.skip`. What happens to this entity at the database level?',
 '["No table or view is generated in the database; the entity exists only as a virtual service-layer construct", "The entity is created as a temporary table", "The entity is deployed to an external OData service", "The annotation is ignored by the CAP compiler"]',
 0,
 '`@cds.persistence.skip` tells the CDS compiler to not generate any database artefact for the entity. It''s used for transient/virtual entities whose data is supplied entirely by custom handlers.',
 'cap-10-entities-types', 4035),

('sap-cap',
 'In CAP with HANA Cloud, when would you use a CDS `view` with `@cds.persistence.table: false` instead of a regular entity?',
 '["When you want a calculated/aggregated database VIEW (not a table) — HANA executes the view SQL at query time", "When you want to hide the entity from OData", "When the entity needs to be read-only", "When the entity has more than 100 columns"]',
 0,
 'A CDS view compiles to a database VIEW. Use this when you need aggregations, joins, or calculated columns evaluated by the HANA engine at runtime rather than materialising data in a table.',
 'cap-36-hana-views', 4036),

('sap-cap',
 'What is the key advantage of using HANA Cloud Calculation Views in combination with CAP services?',
 '["Calculation Views push complex analytics (multi-join, aggregation, hierarchies) entirely to the HANA engine, delivering results faster than equivalent application-layer processing", "They allow CAP to bypass XSUAA authentication", "They replace the need for CDS entities entirely", "They enable CAP to run on-premise"]',
 0,
 'HANA Calculation Views leverage HANA''s in-memory columnar engine for analytic operations. CAP can expose them via CDS views, combining HANA''s analytical power with CAP''s OData and security framework.',
 'cap-36-hana-views', 4037),

('sap-cap',
 'A CAP application stores large JSON blobs in a HANA NCLOB column. A developer proposes instead using a CDS `LargeString` type. Is this correct, and why?',
 '["Yes — CDS LargeString maps to NCLOB in HANA and CLOB in other DBs, providing the correct large text column type in a DB-agnostic way", "No — LargeString is only for SQLite; HANA requires an explicit NCLOB annotation", "No — CAP does not support NCLOB; all strings are VARCHAR(5000)", "Yes — but LargeString maps to BLOB, not NCLOB"]',
 0,
 'CDS built-in types like `LargeString` are mapped to the appropriate database type per adapter. For HANA, `LargeString` compiles to `NCLOB`. This keeps the model DB-agnostic while generating the correct DDL.',
 'cap-34-persistence-basics', 4038),

('sap-cap',
 'What does the `--to hana` flag do when running `cds deploy --to hana` from the project root?',
 '["Generates HDI artefacts and deploys them to the bound HANA Cloud HDI container using the credentials in default-env.json or VCAP_SERVICES", "Generates SQL DDL and prints it to stdout", "Runs the app on HANA Cloud Foundry", "Compresses CDS files for upload to HANA XS Advanced"]',
 0,
 '`cds deploy --to hana` invokes the HDI deploy pipeline: CDS compiles to HDI design-time artefacts, then `@sap/hdi-deploy` pushes them to the HDI container referenced in the service binding.',
 'cap-35-hana-cloud', 4039),

('sap-cap',
 'In which scenario would you use `cds.ql` (tagged template literal) instead of `SELECT.from(Entity).where(...)` in a CAP handler?',
 '["When you need to write a complex query with subselects or expressions that are cleaner to express in CDS query language syntax", "When you need raw SQL passthrough to HANA", "When the query involves more than 5 joins", "cds.ql is deprecated and should never be used"]',
 0,
 '`cds.ql` provides a tagged template literal interface for CQN. Both styles produce the same CQN result; `cds.ql` is preferred when query complexity makes the fluent API verbose.',
 'cap-23-querying-cqn', 4040),

('sap-cap',
 'A CAP service exposes a HANA Full-Text Search across a `Books` entity. Which approach keeps the search database-agnostic during local dev but uses HANA FTS in production?',
 '["Use CAP''s built-in search annotation `@cds.search` on the entity; SQLite handles it with LIKE locally, HANA uses CONTAINS() in production", "Hard-code `CONTAINS(*)` SQL in the handler and guard it with process.env.NODE_ENV", "Use an external Elasticsearch service for both environments", "Full-text search requires a HANA-specific CDS pragma and cannot work locally"]',
 0,
 '`@cds.search` is CAP''s DB-agnostic search annotation. The CAP SQLite adapter translates it to LIKE patterns for local dev; the HANA adapter generates efficient `CONTAINS()` full-text predicates in production.',
 'cap-37-search-features', 4041),

('sap-cap',
 'Why should you avoid large SELECT * queries in CAP handlers that serve OData list endpoints with many records?',
 '["SELECT * fetches all columns including large LargeString/BLOB fields, causing excessive memory use and slow responses; always project only needed columns", "SELECT * is not valid CQN syntax", "CAP automatically rewrites SELECT * to SELECT key fields only", "SELECT * causes HANA licensing issues"]',
 0,
 'Fetching all columns including potentially large text fields for every row in a list is a common performance anti-pattern. Always project (`SELECT.from(Books, b => b.ID, b.title, b.price)`) to limit data transfer.',
 'cap-38-performance-tuning', 4042),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 5: Authentication & Authorization (10 questions) — order_num 4043-4052
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'A CAP service entity is annotated with `@requires: ''authenticated-user''`. What exactly does this enforce?',
 '["Any authenticated user (valid JWT, any role) can access the entity; unauthenticated requests get 401", "Only users with the role ''authenticated-user'' can access it", "The entity requires HANA Cloud authentication", "The annotation has no runtime effect; it is documentation only"]',
 0,
 '`authenticated-user` is a CAP pseudo-role meaning any request with a valid JWT token passes this check. It enforces login without requiring a specific application role.',
 'cap-46-xsuaa-basics', 4043),

('sap-cap',
 'You add `@requires: ''Admin''` to a CDS service entity. Where must the role `Admin` be defined so XSUAA includes it in the JWT token?',
 '["In the xs-security.json file as a role-template, then assigned via a Role Collection in the BTP cockpit", "In package.json under cds.roles", "In the HANA HDI container permissions", "In the SAP Identity Authentication Service (IAS) directly"]',
 0,
 'XSUAA roles flow through: xs-security.json → role-template → role → role collection → user assignment in BTP cockpit. The JWT then carries the `scope` claim that CAP checks against `@requires`.',
 'cap-46-xsuaa-basics', 4044),

('sap-cap',
 'What is the difference between `@requires` and `@restrict` in CDS authorization annotations?',
 '["@requires checks whether the user has any of the listed roles; @restrict provides fine-grained control specifying which operations and optional where-clause filters per grant", "@requires is for entities; @restrict is for services", "@requires is evaluated at the DB level; @restrict at the network level", "They are interchangeable"]',
 0,
 '`@requires` is a shorthand for "user must have at least one of these roles to access this entity at all". `@restrict` allows per-operation grants with optional instance-level `where` conditions for row-level security.',
 'cap-47-restrict-annotation', 4045),

('sap-cap',
 'A user is assigned the role `Viewer` and tries to DELETE a record from an entity annotated `@restrict: [{ grant: ''READ'', to: ''Viewer'' }]`. What response does CAP return?',
 '["403 Forbidden — DELETE is not granted to Viewer; only READ is", "404 Not Found — CAP hides the entity from non-admin users", "401 Unauthorized — the user must re-authenticate", "200 OK — @restrict only applies to GET operations"]',
 0,
 'CAP enforces `@restrict` grants at the framework level. If an operation (DELETE) is not explicitly granted to the user''s role, CAP rejects it with HTTP 403 before any handler code runs.',
 'cap-47-restrict-annotation', 4046),

('sap-cap',
 'You need row-level security: a salesperson can only read their own orders. Which `@restrict` pattern achieves this in CAP?',
 '["@restrict: [{ grant: ''READ'', to: ''Salesperson'', where: ''createdBy = $user'' }]", "@restrict: [{ grant: ''READ'', to: ''Salesperson'', filter: ''userID = jwt.sub'' }]", "@rowlevel: { field: ''createdBy'', user: ''$jwt.email'' }", "@requires: ''Salesperson'' @where: ''createdBy = $me''"]',
 0,
 'The `where` clause in `@restrict` uses CDS pseudo-variables like `$user` (the authenticated user''s ID). CAP appends this condition to all generated SQL WHERE clauses for that entity automatically.',
 'cap-48-instance-auth', 4047),

('sap-cap',
 'When using SAP BTP XSUAA with CAP, the JWT token carries user roles as OAuth 2.0 scopes. In which format does XSUAA typically prefix these scopes in the token?',
 '["<XSUAA-app-name>.<role-name> — e.g. my-app!t12345.Admin", "role:<role-name>", "sap.btp.<role-name>", "urn:sap:identity:<role-name>"]',
 0,
 'XSUAA scopes in the JWT are namespaced with the XSUAA application name and tenant suffix (e.g., `my-cap-app!t12345.Admin`). CAP''s XSUAA adapter strips the prefix when matching against `@requires`/`@restrict` role names.',
 'cap-46-xsuaa-basics', 4048),

('sap-cap',
 'You want to disable authentication entirely for a specific CAP service entity during local development. Which `cds.requires.auth` configuration achieves this?',
 '["Set cds.requires.auth.kind to ''dummy'' or ''mocked'' in the local profile — all requests are treated as authenticated with mock user/roles", "Delete the xs-security.json file", "Set NODE_ENV=development", "Comment out all @requires annotations"]',
 0,
 '`kind: "dummy"` (or `"mocked"`) in `cds.requires.auth` makes CAP accept all requests as authenticated with configurable mock users. This is safe only for local development; never deploy this configuration.',
 'cap-49-mock-auth', 4049),

('sap-cap',
 'What is Principal Propagation in the context of a CAP service calling a downstream SAP system?',
 '["Forwarding the end-user''s identity (JWT) to the downstream system so it can enforce its own authorization, rather than using a technical user", "A load-balancing technique for distributing requests", "A HANA feature for propagating table statistics", "Forwarding the admin user''s credentials to all microservices"]',
 0,
 'Principal Propagation passes the original end-user''s OAuth token to downstream services (like S/4HANA or another CAP service), maintaining the user''s identity chain and enabling fine-grained authorization at each hop.',
 'cap-51-principal-propagation', 4050),

('sap-cap',
 'Your CAP application receives a JWT from IAS (SAP Identity Authentication Service) instead of XSUAA. What CAP configuration supports this?',
 '["cds.requires.auth.kind = ''ias'' — CAP has an IAS adapter for token validation", "Replace XSUAA with IAS in xs-security.json only", "IAS tokens are automatically accepted by the XSUAA adapter without changes", "IAS cannot be used with CAP; XSUAA is mandatory"]',
 0,
 'CAP supports IAS tokens via the `ias` auth kind. On BTP, XSUAA and IAS can be used together (token exchange), and CAP''s auth framework handles both. The configuration determines which token validator runs.',
 'cap-50-ias-integration', 4051),

('sap-cap',
 'In CAP, what does the `cds.User` object represent in a handler, and how do you access the current user''s email?',
 '["cds.User is the authenticated user context; access email via req.user.id or req.user.attr.email depending on IDP configuration", "cds.User is a static class; use cds.User.email as a global", "The email is available in req.headers[''x-user-email''] only", "cds.User is only available in Java CAP, not Node.js"]',
 0,
 '`req.user` in a CAP handler is an instance of `cds.User` populated from the validated JWT. `req.user.id` is the unique user identifier; additional attributes (email, name) come from the IDP''s token claims.',
 'cap-46-xsuaa-basics', 4052),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 6: BTP Services Integration (8 questions) — order_num 4053-4060
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'A CAP application needs to upload and download binary files. Which BTP service provides scalable object storage, and how does CAP access it?',
 '["SAP BTP Object Store Service — CAP connects via the npm package @sap/node-objectstore or a custom handler using the Object Store REST API", "SAP HANA Cloud LargeObject columns — no additional service needed", "SAP Document Management Service — CAP has a built-in DMS adapter", "Content Delivery Network (CDN) — files are pushed via cds deploy"]',
 0,
 'Object Store Service provides S3/Azure Blob/GCS-compatible storage on BTP. CAP handlers use the service binding credentials (endpoint, accessKey) with a compatible SDK to upload/download files outside the DB.',
 'cap-62-object-store', 4053),

('sap-cap',
 'You integrate SAP Job Scheduling Service with your CAP application. What is the correct approach for securing the callback endpoint that the scheduler calls?',
 '["Bind the Job Scheduling Service to your CAP app; protect the callback route with the scheduler''s client credential scope; validate the incoming OAuth token in the handler", "Use basic auth username/password in the callback URL", "Leave the endpoint public — the scheduler IPs are allowlisted by SAP", "Use an API key stored in an environment variable"]',
 0,
 'Job Scheduling Service supports OAuth 2.0 client credential grant. The scheduler obtains a token for your app''s XSUAA instance and sends it in the Authorization header. Your CAP app validates this token using the bound XSUAA service.',
 'cap-64-job-scheduling', 4054),

('sap-cap',
 'Your CAP Node.js service uses `@sap/logging` middleware for the SAP Application Logging Service. What format does this library output logs in?',
 '["JSON structured logs conforming to the SAP Logging Service schema — parsed by Kibana/Elasticsearch in BTP", "Plain text with timestamps", "Binary protobuf format for efficiency", "Syslog RFC 5424 format"]',
 0,
 '`@sap/logging` emits structured JSON logs with correlation IDs, log levels, component names, and other fields expected by the SAP Application Logging Service. Kibana dashboards in BTP parse this schema natively.',
 'cap-65-app-logging', 4055),

('sap-cap',
 'You want to enable a new payment feature for 10% of users as a canary release without redeploying the app. Which BTP service supports this?',
 '["SAP Feature Flags Service — supports boolean and percentage-rollout variants evaluated at runtime", "SAP Continuous Integration & Delivery service", "SAP Cloud Transport Management", "A-B testing is not available on BTP without custom code"]',
 0,
 'Feature Flags Service lets you define flags with variants (boolean, string, rollout percentage). Your CAP service queries the flag at runtime via the Feature Flags REST API and acts accordingly — no redeployment needed.',
 'cap-66-feature-flags', 4056),

('sap-cap',
 'An SAP Build Process Automation workflow needs to notify your CAP service when a task is approved. Which integration pattern is correct?',
 '["Configure an automation''s outbound webhook/callback to POST to a CAP action endpoint, secured with XSUAA client credentials", "Poll the workflow API every 5 seconds from the CAP service", "Use SAP Integration Suite as mandatory middleware", "Write results directly to the CAP application''s HANA database from the automation"]',
 0,
 'SBPA supports outbound webhooks and task completion callbacks. The callback hits a CAP OData action endpoint (POST). Securing it with XSUAA client credentials ensures only the automation can trigger it.',
 'cap-61-sbpa', 4057),

('sap-cap',
 'Your CAP application is packaged as an HTML5 application and uploaded to the HTML5 App Repository. What is the role of the App Router in serving this app to end users?',
 '["AppRouter proxies requests — serving the static HTML5 SPA from the repository and forwarding API calls to the CAP backend with JWT propagation", "AppRouter is a load balancer with no auth involvement", "AppRouter replaces XSUAA for token validation", "AppRouter serves as the database proxy for HANA"]',
 0,
 'AppRouter reads the `xs-app.json` routing config to direct static asset requests to the HTML5 App Repository and backend API calls to CAP (with token forwarding). It also handles the OAuth login flow for browser-based apps.',
 'cap-68-html5-approuter', 4058),

('sap-cap',
 'You add `@sap/xsenv` to your CAP service to read service bindings. What problem does this package solve?',
 '["It parses VCAP_SERVICES (Cloud Foundry) and service binding files (Kubernetes secrets) into a unified JavaScript object, abstracting the runtime differences", "It encrypts environment variables at rest", "It generates xs-security.json from environment variables", "It is the XSUAA client library for token validation"]',
 0,
 '`@sap/xsenv` provides `getServices()` and `getService()` helpers that read from `VCAP_SERVICES` (CF) or mounted Kubernetes secrets transparently. This removes the need for runtime-specific credential parsing in app code.',
 'cap-57-xsuaa-service', 4059),

('sap-cap',
 'A CAP service uses SAP Event Mesh. A consumer microservice subscribes to a topic and receives a CloudEvent. What is the standard field that identifies the event type in the CloudEvent specification?',
 '["type — e.g. sap.cap.Orders.Created.v1", "eventName in the payload body", "X-SAP-Event-Type HTTP header", "subject field in the envelope"]',
 0,
 'The CloudEvents specification defines `type` as the event type identifier (e.g., `sap.cap.Orders.Created.v1`). SAP Event Mesh and CAP''s messaging adapter use this field for routing and consumer filtering.',
 'cap-29-messaging', 4060),

-- ─────────────────────────────────────────────────────────────────────────────
-- MODULE 7: Deployment & Production (10 questions) — order_num 4061-4070
-- ─────────────────────────────────────────────────────────────────────────────
('sap-cap',
 'What is an MTA (Multi-Target Application) in the context of deploying a CAP application to Cloud Foundry?',
 '["A deployment descriptor (mta.yaml) that bundles multiple modules (CAP backend, HTML5 frontend, HDI deployer) and their service dependencies into a single deployable archive (.mtar)", "A multi-tenant architecture pattern", "A monitoring tool for BTP applications", "A load testing framework for CAP services"]',
 0,
 'MTA is SAP''s standard for deploying multi-module BTP applications. The `mta.yaml` declares modules (CF apps), resources (BTP service instances), and inter-module dependencies. `mbt build` packages it; `cf deploy` applies it.',
 'cap-69-mta-intro', 4061),

('sap-cap',
 'You run `mbt build -t ./` and get a `.mtar` file. What is the next command to deploy it to Cloud Foundry?',
 '["cf deploy <file>.mtar", "cf push <file>.mtar", "cds deploy --mtar <file>.mtar", "kubectl apply -f <file>.mtar"]',
 0,
 '`cf deploy` is the CF MTA Deploy Plugin command. It reads the `.mtar`, creates/updates service instances, runs the HDI deployer, and starts/restarts CF apps in the correct order based on `mta.yaml` dependencies.',
 'cap-70-cf-deploy', 4062),

('sap-cap',
 'What is the key advantage of Blue-Green deployment for a CAP application on Cloud Foundry?',
 '["It runs the new version alongside the old; after validation, traffic switches instantly to the new version with near-zero downtime and a fast rollback path", "It deploys the app in two regions simultaneously for HA", "It uses two HANA Cloud instances for failover", "It enables A/B testing of UI components"]',
 0,
 'Blue-Green deployment maintains two identical environments. The new (green) version is deployed and tested while the old (blue) serves live traffic. Route switching redirects users to green with zero downtime; blue stays as instant rollback.',
 'cap-72-blue-green', 4063),

('sap-cap',
 'Your CAP application needs 3 BTP service instances: HANA Cloud, XSUAA, and Event Mesh. Where are these declared when using MTA deployment?',
 '["In the `resources:` section of mta.yaml, each with type sap.btp.service-instance and their service/plan names", "In VCAP_SERVICES environment variable set manually before deployment", "In package.json cds.requires only", "In the CF manifest.yml services array"]',
 0,
 'MTA `resources` of type `sap.btp.service-instance` instruct the CF MTA plugin to create or bind existing service instances. This makes the full infrastructure reproducible from the `mta.yaml` alone.',
 'cap-69-mta-intro', 4064),

('sap-cap',
 'After deploying a CAP application to Cloud Foundry, a developer changes one CDS entity. What is the minimum correct sequence to get the change live?',
 '["1. Update the CDS model, 2. rebuild the MTA with `mbt build`, 3. `cf deploy` the new .mtar — this re-runs HDI migration and restarts the app", "1. `cf push` the Node.js app only — no HDI step needed for CDS changes", "1. Run `cds deploy --to hana` from the developer laptop against production", "1. Restart the CF app with `cf restart` — CDS changes are picked up automatically"]',
 0,
 'Schema changes require HDI migration (re-running the HDI deployer). The full MTA build and deploy cycle ensures the HDI artefacts are regenerated and applied before the new app version starts.',
 'cap-70-cf-deploy', 4065),

('sap-cap',
 'You want to monitor your CAP application''s response times and error rates on BTP. Which SAP service provides this out of the box for CF-deployed apps?',
 '["SAP Cloud ALM or SAP Dynatrace integration via the BTP cockpit — they collect metrics from CF app instances automatically", "Only manual New Relic APM integration works with CAP", "CAP has no monitoring support; you must build a custom dashboard", "SAP HANA Cloud Studio provides app-level monitoring"]',
 0,
 'BTP integrates with SAP Cloud ALM for operations monitoring (health checks, alerting) and with Dynatrace (via BTP service) for APM. CF also provides the `cf logs` command and Application Logging Service for diagnostics.',
 'cap-74-monitoring', 4066),

('sap-cap',
 'Your production CAP service occasionally receives requests with extremely large OData `$filter` expressions, causing CPU spikes. Which production hardening technique addresses this?',
 '["Implement an express middleware that validates and caps the length/complexity of incoming $filter expressions before CAP processes them", "Disable OData $filter support entirely", "Add more CF instances to handle the load", "Switch from HANA Cloud to SQLite in production"]',
 0,
 'Input validation middleware (e.g., checking `req.query.$filter` length or blocking deeply nested logical operators) protects against denial-of-service via complex queries. Combined with CF autoscaling, it provides a robust defence.',
 'cap-78-security-hardening', 4067),

('sap-cap',
 'What does the SAP BTP Multitenancy pattern require from a CAP application compared to a single-tenant deployment?',
 '["The CAP app must onboard tenants via a subscription callback, provision per-tenant HDI containers, and route each request to the correct tenant''s schema using the JWT tenant ID", "Only a single HANA Cloud schema is needed; tenants share tables", "Multitenancy requires switching from Node.js to Java CAP runtime", "Each tenant gets a separate CF app instance"]',
 0,
 'CAP multitenancy uses the `@sap/cds-mtxs` extension. It handles subscription (create HDI container per tenant), upgrade (deploy schema changes to all tenants), and request routing (select the tenant DB from the JWT `zid` claim).',
 'cap-76-multitenancy', 4068),

('sap-cap',
 'You are building a CI/CD pipeline for a CAP application using SAP Continuous Integration & Delivery service. Which two artefacts does the pipeline typically produce?',
 '["A .mtar archive (from mbt build) and container images for the HDI deployer — both pushed to the deploy stage", "A .war file and a Docker Compose manifest", "A Helm chart and a HANA export file", "A Cloud Foundry manifest.yml and a ZIP of the CDS files"]',
 0,
 'The standard SAP CI/CD pipeline for CAP runs `mbt build` to produce the `.mtar` and optionally builds container images. The deploy stage calls `cf deploy` with the `.mtar` against the target CF space.',
 'cap-73-cicd', 4069),

('sap-cap',
 'You are doing a final go-live check for your CAP application. Which THREE checks are most critical before flipping the production route?',
 '["1. Verify all XSUAA role collections are assigned, 2. confirm HDI migration succeeded with no errors, 3. run a smoke test hitting key OData endpoints with a valid JWT", "1. Check the Node.js version, 2. run ESLint, 3. verify package-lock.json is committed", "1. Ensure SQLite is disabled, 2. test with dummy auth, 3. check CF memory quota", "1. Verify DNS TTL, 2. confirm HANA table counts, 3. test the Fiori Launchpad tile"]',
 0,
 'The three production-critical checks are: auth (role collections assigned so real users can log in), schema (HDI migration clean so the DB matches the new code), and functional (smoke test with a real JWT confirms the service is live and responding).',
 'cap-80-go-live', 4070);
