-- Module 10 topics for dev-quickstart


INSERT INTO topics (module_id, number, slug, title, focus, description, content_md, order_index, status) VALUES (
  (SELECT id FROM modules WHERE course_id = 'dev-quickstart' AND number = '10'),
  '730',
  'dev-qs-cap-java-prereqs',
  'Java SDK & Maven Setup',
  'Install Java 21 and Maven, and configure JAVA_HOME',
  'Download and install OpenJDK 21 (LTS), install Maven 3.9, set JAVA_HOME correctly, and verify both tools are on the PATH.',
  '# Java SDK & Maven Setup

CAP Java projects run on Spring Boot and require Java 17 or 21 (LTS).

## Install Java 21 (OpenJDK)

### macOS — using Homebrew

```bash
brew install openjdk@21
# Follow the caveats to add to PATH:
echo ''export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"'' >> ~/.zshrc
source ~/.zshrc
```

### Windows — using the installer

1. Download from [adoptium.net](https://adoptium.net) — select **JDK 21**, **Windows**, **x64**
2. Run the `.msi` installer — check **Set JAVA_HOME** in the optional features

### Linux (Ubuntu/Debian)

```bash
sudo apt install openjdk-21-jdk
```

### Verify

```bash
java --version
# openjdk 21.x.x

javac --version
# javac 21.x.x
```

## Set JAVA_HOME (if not set automatically)

### macOS / Linux — add to ~/.zshrc or ~/.bashrc

```bash
export JAVA_HOME=$(/usr/libexec/java_home -v 21)   # macOS
# or
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64  # Linux

export PATH=$JAVA_HOME/bin:$PATH
```

Reload: `source ~/.zshrc`

### Windows — System Environment Variables

1. Search for **Environment Variables** in Start
2. Under **System Variables** → New:
   - Name: `JAVA_HOME`
   - Value: `C:\Program Files\Eclipse Adoptium\jdk-21.x.x.x-hotspot`
3. Edit **Path** → Add `%JAVA_HOME%in`

## Install Maven 3.9

### macOS

```bash
brew install maven
```

### Linux

```bash
sudo apt install maven
```

### Windows

Download from [maven.apache.org](https://maven.apache.org/download.cgi) → unzip → add `bin/` to PATH.

### Verify

```bash
mvn --version
# Apache Maven 3.9.x
# Java version: 21.x.x
```

Make sure Maven reports the correct Java version. If it shows Java 11 or 17, your `JAVA_HOME` isn''t set for Maven.
',
  0,
  'published'
);


INSERT INTO topics (module_id, number, slug, title, focus, description, content_md, order_index, status) VALUES (
  (SELECT id FROM modules WHERE course_id = 'dev-quickstart' AND number = '10'),
  '731',
  'dev-qs-cap-java-init',
  'Generate a CAP Java Project',
  'Scaffold a CAP Java project using cds init and understand the Maven structure',
  'Use cds init with the java template to scaffold a Spring Boot CAP project, understand the Maven module layout, and add a sample service.',
  '# Generate a CAP Java Project

CAP Java projects are Maven multi-module Spring Boot applications generated by the CDS CLI.

## Generate the project

```bash
cds init bookshop-java --add java
cd bookshop-java
```

Or use Maven archetypes directly:

```bash
mvn archetype:generate -DarchetypeArtifactId=cds-services-archetype \
    -DarchetypeGroupId=com.sap.cds \
    -DarchetypeVersion=RELEASE \
    -DgroupId=com.mycompany \
    -DartifactId=bookshop-java
```

## Project structure

```
bookshop-java/
├── db/
│   └── schema.cds                   ← same CDS data model as Node.js
├── srv/
│   ├── cat-service.cds              ← same service definition
│   └── src/main/java/
│       └── com/mycompany/
│           └── CatalogServiceHandler.java  ← Java event handler
├── app/                             ← optional Fiori UI
├── pom.xml                          ← root Maven POM
└── srv/pom.xml                      ← service module POM
```

## Root pom.xml highlights

```xml
<parent>
  <groupId>com.sap.cds</groupId>
  <artifactId>cds-starter-spring-boot</artifactId>
  <version>RELEASE</version>
</parent>

<dependencies>
  <dependency>
    <groupId>com.sap.cds</groupId>
    <artifactId>cds-starter-spring-boot</artifactId>
  </dependency>
  <!-- SQLite for local dev -->
  <dependency>
    <groupId>org.xerial</groupId>
    <artifactId>sqlite-jdbc</artifactId>
    <scope>runtime</scope>
  </dependency>
</dependencies>
```

## Add a sample service handler (Java)

`srv/src/main/java/com/mycompany/CatalogServiceHandler.java`:

```java
@Component
@ServiceName(CatalogService_.CDS_NAME)
public class CatalogServiceHandler implements EventHandler {

    @Before(event = CqnService.EVENT_READ, entity = Books_.CDS_NAME)
    public void beforeReadBooks(CdsReadEventContext context) {
        System.out.println("Reading books for user: " + context.getUserInfo().getName());
    }
}
```

## Add data

Create `db/data/bookshop-Books.csv` — same CSV format as Node.js:

```csv
ID,title,author,stock,price
1,The Hobbit,J.R.R. Tolkien,100,14.99
2,Dune,Frank Herbert,75,12.50
```

## Build and run (next topic)

```bash
mvn spring-boot:run
```
',
  1,
  'published'
);


INSERT INTO topics (module_id, number, slug, title, focus, description, content_md, order_index, status) VALUES (
  (SELECT id FROM modules WHERE course_id = 'dev-quickstart' AND number = '10'),
  '732',
  'dev-qs-cap-java-run',
  'Run & Stop the CAP Java Server',
  'Start and stop the Spring Boot server and access OData endpoints',
  'Run the CAP Java project using Maven, read the Spring Boot startup output, access OData endpoints at port 8080, and stop the server cleanly.',
  '# Run & Stop the CAP Java Server

## Start the server

```bash
cd bookshop-java
mvn spring-boot:run
```

First run downloads Maven dependencies (~2-3 minutes). Subsequent runs are much faster.

## Understanding the startup output

```
  .   ____          _            __ _ _
 /\\ / ___''_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | ''_ | ''_| | ''_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  ''  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v3.x.x)

...
[cds] - model loaded from 2 file(s)
[cds] - connect using SQLite in-memory
[cds] - serving CatalogService { path: ''/catalog'' }
...
Tomcat started on port(s): 8080
Started Application in 4.321 seconds
```

## Access OData endpoints

```
http://localhost:8080/catalog/$metadata
http://localhost:8080/catalog/Books
http://localhost:8080/catalog/Books?$top=2
```

> Note: CAP Java defaults to port **8080**, not 4004 like CAP Node.js.

## Stop the server

Press `Ctrl+C` in the terminal.

## Change the port

In `srv/src/main/resources/application.yaml`:

```yaml
server:
  port: 4004
```

## Run with a specific Spring profile

```bash
mvn spring-boot:run -Dspring-boot.run.profiles=production
```

## Skip tests during run (faster startup)

```bash
mvn spring-boot:run -DskipTests
```

## Useful log levels for debugging

In `application.yaml`:

```yaml
logging:
  level:
    com.sap.cds: DEBUG       # show CDS framework internals
    org.springframework: INFO
    root: WARN
```

## Hot reload (devtools)

Add to `pom.xml` dependencies:

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-devtools</artifactId>
  <optional>true</optional>
</dependency>
```

Now when you save a Java file, Maven rebuilds and the server restarts automatically — similar to `cds watch`.
',
  2,
  'published'
);


INSERT INTO topics (module_id, number, slug, title, focus, description, content_md, order_index, status) VALUES (
  (SELECT id FROM modules WHERE course_id = 'dev-quickstart' AND number = '10'),
  '733',
  'dev-qs-cap-java-debug',
  'Debugging CAP Java with VS Code',
  'Attach the VS Code Java debugger to a running Spring Boot CAP server',
  'Configure VS Code to launch or attach to a CAP Java Spring Boot app, set breakpoints in event handlers, and inspect request context at runtime.',
  '# Debugging CAP Java with VS Code

The **Extension Pack for Java** and **Spring Boot Extension Pack** give you a full Java debugger inside VS Code.

## Required extensions

- Extension Pack for Java (Microsoft)
- Spring Boot Extension Pack (VMware)

Install both from the VS Code Extensions panel.

## Method 1 — Launch from VS Code (easiest)

Create `.vscode/launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "CAP Java (Spring Boot)",
      "request": "launch",
      "mainClass": "com.mycompany.Application",
      "projectName": "bookshop-java",
      "args": "",
      "vmArgs": "-Dspring.profiles.active=default"
    }
  ]
}
```

Press `F5` — VS Code compiles and starts the server with the debugger attached.

## Method 2 — Attach to mvn spring-boot:run

### Step 1 — start Maven with remote debug

```bash
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```

### Step 2 — add an attach config to launch.json

```json
{
  "type": "java",
  "name": "Attach to CAP Java",
  "request": "attach",
  "hostName": "localhost",
  "port": 5005
}
```

Run **Attach to CAP Java** from the Debug panel.

## Set a breakpoint in an event handler

Open `CatalogServiceHandler.java`, click the line gutter:

```java
@Before(event = CqnService.EVENT_READ, entity = Books_.CDS_NAME)
public void beforeReadBooks(CdsReadEventContext context) {
    // ← breakpoint here
    System.out.println("User: " + context.getUserInfo().getName());
}
```

Send a GET request to `http://localhost:8080/catalog/Books` — VS Code pauses at the breakpoint.

## Inspect the context object

In the VS Code **Variables** panel when paused you can expand:

- `context` → see `userInfo`, `cqn` (the query), `parameters`
- `context.getUserInfo()` → logged-in user details

## Spring Boot Dashboard

After installing the Spring Boot Extension Pack, a **Spring Boot Dashboard** appears in the left sidebar. It shows:

- Running apps with start/stop controls
- Active beans list
- Mapped HTTP endpoints

Click any endpoint to open it directly in the browser.
',
  3,
  'published'
);
