export const COURSES = [
  {
    id: "sap-btp",
    title: "SAP BTP & CAP Development",
    subtitle: "Build cloud-native apps on SAP Business Technology Platform",
    description: "Go from zero to a fully deployed SAP BTP application. You'll master SAPUI5 for the frontend, CAP for the backend, and deploy on BTP with CI/CD pipelines — all in one structured course.",
    status: "available",
    badge: null,
    icon: "🛠️",
    accentColor: "#0070F3",
    accentLight: "#e8f3ff",
    tags: ["CAP", "SAPUI5", "BTP", "Node.js"],
    level: "Beginner → Advanced",
    estimatedHours: 40,
    modules: 6,
    topics: 20,
    highlights: [
      "Build SAPUI5 apps with XML views & OData binding",
      "Design CDS models and expose REST/OData services",
      "Integrate frontend + backend end-to-end on BTP",
      "Deploy with CI/CD pipelines to Cloud Foundry",
    ],
    apiBase: "/api",
  },
  {
    id: "sap-ai",
    title: "SAP AI Core & Generative AI",
    subtitle: "Build AI-powered apps with SAP Generative AI Hub",
    description: "Learn to build Generative AI solutions using SAP AI Core and Gen AI Hub. Master prompt engineering, embeddings, RAG pipelines, function calling, and production-ready AI patterns — all without needing real API keys.",
    status: "available",
    badge: null,
    icon: "🤖",
    accentColor: "#7C3AED",
    accentLight: "#f0ebff",
    tags: ["AI Core", "Gen AI Hub", "LangChain", "MCP", "Agentic AI"],
    level: "Intermediate → Advanced",
    estimatedHours: 70,
    modules: 9,
    topics: 46,
    highlights: [
      "Connect to SAP Generative AI Hub with OpenAI-compatible API",
      "Build RAG pipelines with HANA Vector Engine & embeddings",
      "Implement MCP servers, LangGraph agents & A2A protocol",
      "Apply production patterns: retry, caching, guardrails, monitoring",
    ],
    apiBase: "/api",
  },
  {
    id: "sap-is",
    title: "SAP Integration Suite",
    subtitle: "Build enterprise integrations with SAP Integration Suite & iFlows",
    description: "Master SAP Integration Suite to connect cloud and on-premise systems. Build iFlows with adapters, mappings, and error handling — then deploy and monitor real-world integration scenarios on BTP.",
    status: "coming_soon",
    badge: null,
    icon: "🔌",
    accentColor: "#E8590C",
    accentLight: "#fff2ec",
    tags: ["iFlow", "OData", "SOAP", "REST", "CPI"],
    level: "Intermediate",
    estimatedHours: 30,
    modules: 5,
    topics: 18,
    highlights: [
      "Configure adapters: HTTP, OData, SOAP, SFTP, IDoc",
      "Design message mappings and content modifiers",
      "Implement error handling and monitoring strategies",
      "Deploy and operate integrations on SAP BTP",
    ],
    apiBase: "/api",
  },
  {
    id: "sde-to-fde",
    title: "SDE to Forward-Deployed Engineer",
    subtitle: "From writing code to deploying it at enterprise customers",
    description: "Go from pure software engineering to the full FDE skillset. Learn customer discovery, solution architecture, demo delivery, PoC design, implementation planning, incident management, executive communication, and career growth — everything you need to work directly with enterprise customers.",
    status: "coming_soon",
    badge: null,
    icon: "⚡",
    accentColor: "#1D6FE8",
    accentLight: "#e8f0ff",
    tags: ["Customer Success", "Pre-Sales", "Solutioning", "Delivery", "Career"],
    level: "Intermediate → Senior",
    estimatedHours: 35,
    modules: 6,
    topics: 21,
    highlights: [
      "Run technical discovery calls and map customer pain to solutions",
      "Build and deliver demos and PoCs that close deals",
      "Lead implementations, incidents, and customer handoffs",
      "Communicate with executives and grow your FDE career",
    ],
    apiBase: "/api",
  },
];

export function getCourse(id) {
  return COURSES.find((c) => c.id === id) || null;
}
